# **Introdução ao Projeto: Análise dos Dados da PNAD COVID19 de 2020**
A Pesquisa Nacional por Amostra de Domicílios (PNAD) COVID19, conduzida pelo IBGE em 2020, foi uma iniciativa pioneira para mensurar os impactos sociais e econômicos causados pela pandemia no Brasil. Este projeto utiliza os dados públicos dessa pesquisa com o objetivo de extrair informações relevantes para subsidiar a compreensão de padrões e tendências que emergiram durante o período crítico da pandemia.

# Objetivo do Projeto
O objetivo principal é transformar os dados brutos da PNAD COVID19 em insights claros e acessíveis, que possam ser apresentados de maneira objetiva para um público não técnico. Para isso, adotaremos as seguintes etapas:

**Período de Análise:**

Seleção de pelo menos 5 meses consecutivos dentro do ano de 2020.

**Seleção de Variáveis:**

Foi escolhidas 15 questões da pesquisa que ofereçam um panorama amplo e diversificado sobre os temas relacionados à COVID-19, como saúde, renda, trabalho e acesso a serviços de saúde.

**Modelagem e Organização dos Dados:**

Ferramentas utilizadas: SQL e Python.
Os dados serão tratados, organizados e modelados para facilitar análises posteriores.
Python será usado para pré-processamento de dados, criação de análises estatísticas e automatização de processos, enquanto o SQL será utilizado para consultas e organização dos dados.
Comentários serão incluídos em cada passo do código para documentar o processo e garantir a reprodutibilidade.

**Análise Descritiva e Geração de Insights:**

Será realizada uma análise descritiva detalhada para identificar padrões, tendências e relações entre as variáveis escolhidas.
Python será usado para visualização gráfica e geração de insights a partir de bibliotecas como Pandas, Matplotlib e Seaborn.

**Visualização dos Resultados:**

Ferramentas utilizadas: Power BI e Python.
Dashboards interativos serão criados no Power BI para apresentar os resultados de forma visualmente atrativa e compreensível.
Python poderá ser utilizado para criar gráficos complementares e realizar análises adicionais de visualização.

**Apresentação Final:**

Todos os resultados serão compilados em uma apresentação voltada para um público não técnico.
O foco será a clareza e a ênfase nos insights práticos, traduzindo os resultados em informações úteis e aplicáveis.


**Importância do Projeto**

A pandemia da COVID-19 trouxe desafios únicos que impactaram diferentes aspectos da vida da população brasileira. Com este trabalho, buscamos destacar esses impactos e contribuir para o entendimento das mudanças sociais e econômicas provocadas pela pandemia, oferecendo insights que podem apoiar na formulação de políticas públicas e estratégias de recuperação.

# Reconhecimento da Base e das Variáveis Disponíveis

Para dar início ao projeto, realizamos o reconhecimento inicial da base de dados da PNAD COVID19. O objetivo desta etapa foi organizar e preparar o dataset para as análises subsequentes. Seguem os passos realizados:

**Download e Organização dos Dados:**

Baixamos o histórico referente a cinco meses consecutivos da pesquisa, disponibilizado no site oficial.
Os dados foram fornecidos em diferentes arquivos, organizados por mês.

**Ajustes dos Nomes das Colunas:**

*   Utilizamos o Excel para renomear as colunas do dataset.
*   Para tornar os nomes das colunas mais intuitivos, seguimos o significado de cada variável, conforme descrito no dicionário de dados fornecido pelo IBGE.Essa padronização facilita a interpretação das variáveis durante as etapas de análise.



**Separação Mensal dos Dados:**

Como o volume de dados é elevado, os meses foram mantidos em planilhas separadas inicialmente.
Essa abordagem permitiu lidar com o tamanho da base de maneira mais eficiente durante o processo de limpeza e organização.


**União dos Dados em um Único DataFrame:**

Para facilitar o tratamento e a análise, todas as planilhas mensais serão consolidadas em um único DataFrame utilizando Python. Essa integração permitirá a aplicação de técnicas de análise e visualização de forma consistente e integrada.


# De para de variaveis seguindo o dicionário fornecido

**1. Leitura da Base de Dados**
O primeiro passo foi carregar uma base de dados em formato CSV que contém informações relacionadas à pandemia de COVID-19 no Brasil. O arquivo foi lido com a biblioteca pandas e transformado em um DataFrame (df), que permite manipular os dados de forma tabular.

**2. Criação de Dicionários para Mapeamento**
Diversos dicionários foram criados com base no dicionário disponibilizado pelo IBGE. Esses dicionários têm a finalidade de traduzir códigos numéricos presentes na base de dados em descrições mais compreensíveis. Alguns exemplos de dicionários criados:

**UF para Estados:** Transforma códigos de unidades federativas (como 35 para São Paulo) nos respectivos nomes dos estados.

**UF para Capitais:** Associa códigos de estados às suas capitais.

**Situação do domicílio: **Traduz códigos numéricos em categorias como "Urbana" ou "Rural".

Outros dicionários foram criados para categorias como sintomas, teste de COVID-19, situação de trabalho, auxílio emergencial, aluguel, entre outros.

Esses mapeamentos tornam os dados mais legíveis e interpretáveis.


**3. Identificação e Exclusão de Colunas Desnecessárias**

Algumas colunas foram identificadas como não relevantes para a análise ou redundantes. Para isso:

Foi usada uma expressão regular (regex) para encontrar colunas cujos nomes começam com letras maiúsculas e terminam com números.

Além disso, uma lista específica de colunas consideradas irrelevantes foi definida manualmente. Exemplos dessas colunas incluem:


*   Semana no mês
*   Peso do domicílio e das pessoas
*   Projeção da população
*   Região Metropolitana e Região Administrativa Integrada



**Essas colunas foram removidas do DataFrame usando o método drop.**

**4. Mapeamento das Variáveis**

Cada coluna relevante do DataFrame foi traduzida para descrições legíveis, utilizando os dicionários de mapeamento criados anteriormente. Por exemplo:

A coluna UF teve seus valores numéricos substituídos pelos nomes dos estados, como 35 para "São Paulo".

A coluna Situação do domicílio foi mapeada para valores como "Urbana" ou "Rural".

Colunas relacionadas a sintomas, como "Flag febre" ou "Flag tosse", foram traduzidas para "Sim" ou "Não".

Informações sobre contratos de trabalho, escolaridade, e auxílio emergencial foram traduzidas para descrições compreensíveis, como "Sim, tem carteira de trabalho assinada" ou "Sim, recebeu auxílio emergencial".


**5. Tratamento de Valores Nulos**
Durante o mapeamento, algumas colunas apresentaram valores nulos, que surgiram porque alguns códigos na base de dados original não estavam presentes nos dicionários de mapeamento. Esses valores nulos foram tratados substituindo-os por uma categoria genérica chamada "Desconhecido". Isso foi feito em colunas como:

UF (Unidade Federativa)
CAPITAL (Capital do estado)
Situação do domicílio


**6. Iteração em Grupos de Colunas**

Para otimizar o processo de mapeamento em colunas com categorias similares (por exemplo, sintomas, testes de COVID, resultados de testes), foram usados laços de repetição (for). Esses laços verificaram se a coluna existe no DataFrame antes de aplicar o mapeamento, garantindo que nenhuma operação fosse realizada em colunas ausentes.

Exemplos de colunas mapeadas em grupo:

Colunas de sintomas, como "Flag febre", "Flag dor de cabeça", etc.
Colunas de testes, como "Flag teste covid" ou "Flag resultado teste covid (sanguíneo)".
Colunas relacionadas a condições de saúde, como "Flag diabete" e "Flag hipertensão".


**7. Exportação do DataFrame Tratado**

Após o tratamento e mapeamento, o DataFrame resultante foi salvo em um novo arquivo CSV. Esse arquivo consolidado pode ser usado em análises posteriores, garantindo que os dados estejam padronizados e fáceis de interpretar.


In [ ]:
# Este script foi desenvolvido para transformar e modelar variáveis de uma base de dados contendo informações da PNAD COVID-19,
# fornecida pelo IBGE. A base é bastante volumosa, com aproximadamente 1,9 milhões de registros, e foi processada no software Spyder,
# devido ao seu desempenho eficiente com grandes volumes de dados.

# O principal objetivo foi aplicar um mapeamento detalhado aos dados e preparar a base para análises posteriores, tornando as variáveis
# mais interpretáveis.


##Importando as bibliotecas necessárias##
import pandas as pd
import re


df = pd.read_csv(r'C:\Users\monica\Downloads\base_covid_unificada.csv') #caminho da base que exportamos em excel e unimos todos os meses

# Dicionário de mapeamento de códigos utilizabdo o de para do dícionário
uf_para_estado = {
    11: "Rondônia",
    12: "Acre",
    13: "Amazonas",
    14: "Roraima",
    15: "Pará",
    16: "Amapá",
    17: "Tocantins",
    21: "Maranhão",
    22: "Piauí",
    23: "Ceará",
    24: "Rio Grande do Norte",
    25: "Paraíba",
    26: "Pernambuco",
    27: "Alagoas",
    28: "Sergipe",
    29: "Bahia",
    31: "Minas Gerais",
    32: "Espírito Santo",
    33: "Rio de Janeiro",
    35: "São Paulo",
    41: "Paraná",
    42: "Santa Catarina",
    43: "Rio Grande do Sul",
    50: "Mato Grosso do Sul",
    51: "Mato Grosso",
    52: "Goiás",
    53: "Distrito Federal"
}

uf_para_capital = {
    11: "Município de Porto Velho (RO)",
    12: "Município de Rio Branco (AC)",
    13: "Município de Manaus (AM)",
    14: "Município de Boa Vista (RR)",
    15: "Município de Belém (PA)",
    16: "Município de Macapá (AP)",
    17: "Município de Palmas (TO)",
    21: "Município de São Luís (MA)",
    22: "Município de Teresina (PI)",
    23: "Município de Fortaleza (CE)",
    24: "Município de Natal (RN)",
    25: "Município de João Pessoa (PB)",
    26: "Município de Recife (PE)",
    27: "Município de Maceió (AL)",
    28: "Município de Aracaju (SE)",
    29: "Município de Salvador (BA)",
    31: "Município de Belo Horizonte (MG)",
    32: "Município de Vitória (ES)",
    33: "Município de Rio de Janeiro (RJ)",
    35: "Município de São Paulo (SP)",
    41: "Município de Curitiba (PR)",
    42: "Município de Florianópolis (SC)",
    43: "Município de Porto Alegre (RS)",
    50: "Município de Campo Grande (MS)",
    51: "Município de Cuiabá (MT)",
    52: "Município de Goiânia (GO)",
    53: "Município de Brasília (DF)"
}

situacao_domicilio= {
    1: "Urbana",
    2: "Rural"
}

# Dicionário de mapeamento de códigos para descrições de parentesco
codigo_para_parentesco = {
    1: "Pessoa responsável pelo domicílio",
    2: "Cônjuge ou companheiro(a) de sexo diferente",
    3: "Cônjuge ou companheiro(a) do mesmo sexo",
    4: "Filho(a) do responsável e do cônjuge",
    5: "Filho(a) somente do responsável",
    6: "Filho(a) somente do cônjuge",
    7: "Genro ou nora",
    8: "Pai, mãe, padrasto ou madrasta",
    9: "Sogro(a)",
    10: "Neto(a)",
    11: "Bisneto(a)",
    12: "Irmão ou irmã",
    13: "Avô ou avó",
    14: "Outro parente",
    15: "Agregado(a) - Não parente que não compartilha despesas",
    16: "Convivente - Não parente que compartilha despesas",
    17: "Pensionista",
    18: "Empregado(a) doméstico(a)",
    19: "Parente do(a) empregado(a) doméstico(a)"
}

codigo_para_sexo = {
    1: "Homem",
    2: "Mulher"
}

codigo_para_raca = {
    1: "Branca",
    2: "Preta",
    3: "Amarela",
    4: "Parda",
    5: "Indígena",
    6: "Ignorado"
}

# Dicionário de mapeamento de códigos para descrições de escolaridade
codigo_para_escolaridade = {
    1: "Sem instrução",
    2: "Fundamental incompleto",
    3: "Fundamental completo",
    4: "Médio incompleto",
    5: "Médio completo",
    6: "Superior incompleto",
    7: "Superior completo",
    8: "Pós-graduação, mestrado ou doutorado"
}

codigo_para_tipoEscola = {
    1: "Pública",
    2: "Privada"
}

# Dicionário de mapeamento de códigos para descrições de formato de ensino
codigo_para_formato_ensino = {
    1: "Sim, normalmente",
    2: "Sim, mas apenas parcialmente",
    3: "Não, e meu normalmente é presencial/semipresencial",
    4: "Não, meu curso é online"
}

# Dicionário de mapeamento de códigos para descrições de realização de atividades
codigo_para_realizacao_atividades = {
    1: "Sim, e realizou pelo menos parte delas",
    2: "Sim, mas não realizou (por qualquer motivo)",
    3: "Não",
    4: "Não, porque estava de férias",
    5: "Não aplicável"
}

codigo_para_motivos_em_casa = {
    1: "Sim, e realizou pelo menos parte delas",
    2: "Sim, mas não realizou (por qualquer motivo)",
    3: "Não",
    4: "Não, porque estava de férias"
}

codigo_para_motivos_nao_realizou = {
    1: "Não tinha computador / tablet / celular disponível",
    2: "Não tinha acesso à internet ou a qualidade dela era insuficiente",
    3: "Por problemas de saúde da própria pessoa",
    4: "Tinha que cuidar dos afazeres domésticos, do(s) filhos ou de outro(s) parentes",
    5: "Não conseguiu se concentrar",
    6: "Outro motivo. Especifique."
}

codigo_para_dias = {
    1: "1 dia",
    2: "2 dias",
    3: "3 dias",
    4: "4 dias",
    5: "5 dias",
    6: "6 ou 7 dias"
}

codigo_para_descricao = {
    1: "Sim",
    2: "Não",
    3: "Não sabe",
    9: "Ignorado"
}


codigo_para_resultado = {
    1: "Positivo",
    2: "Negativo",
    3: "Inconclusivo",
    4: "Ainda não recebeu o resultado",
    9: "Ignorado"
}

colunas_para_mapear_sintomas = [
    'Flag febre', 'Flag tosse', 'Flag dor de garganta', 'Flag problemas respiratórios',
    'Flag dor de cabeça', 'Flag dor no peito', 'Flag nausea',
    'Flag nariz escorrendo/entupido', 'Flag Fadiga', 'Flag dor nos olhos',
    'Flag perda de sentidos', 'Flag dor muscular', 'Flag diarreia'
]


colunas_para_mapear_teste = [
    'Ida ao serviço de saúde', 'optou por ficar em casa',
       'Optou por ligar para um profissional', 'Optou pela auto medicação',
       'Seguiu a orientação profissional',
       'Optou por receber a visita de um profissional da saúde SUS',
       'Optou por receber a visita de um profissional da saúde PARTICULAR',
       'Providência tomada foi outra',
       'Local que buscou atendimento foi posto/UBS',
       'Local que buscou atendimento foi pronto socorro do SUS/UPA',
       'Local que buscou atendimento foi hospital do SUS',
       'Local que buscou atendimento foi ambulatório ou consultório privado ',
       'Local que buscou atendimento foi pronto socorro privado',
       'Local que buscou atendimento foi hospital privado', 'Flag internação',
       'Flag procedimentos', 'Flag Plano de saúde', 'Flag teste covid',
       'tipo do teste (cotonete)'
]

colunas_para_mapear_teste_resultado = [
'Flag resultado teste covid (cotonete)', 'Flag resultado teste covid (sanguineo)'
]

colunas_para_mapear_flag_teste = [
'Flag diabete', 'Flag hipertensão', 'Flag doenças respiratórias',
'Flag doenças cardiovasculares', 'Flag trastorno depressivo',
'Flag doenças cancerigenas'
]

codigo_para_restricao = {
    1: "Não fez restrição, levou vida normal como antes da pandemia",
    2: "Reduziu o contato com as pessoas, mas continuou saindo de casa para trabalho ou atividades não essenciais e/ou recebendo visitas",
    3: "Ficou em casa e só saiu em caso de necessidade básica",
    4: "Ficou rigorosamente em casa",
    9: "Ignorado"
}


codigo_para_descricao_papel_trabalho = {
    1: "Trabalhador doméstico (empregado doméstico, cuidados, babá)",
    2: "Militar do exército, marinha ou aeronáutica",
    3: "Policial militar ou bombeiro militar",
    4: "Empregado do setor privado",
    5: "Empregado do setor público (inclusive empresas de economia mista)",
    6: "Empregador",
    7: "Conta própria",
    8: "Trabalhador familiar não remunerado em ajuda a membro do domicílio ou parente",
    9: "Estava fora do mercado de trabalho (fazia apenas afazeres domésticos, cuidados de pessoas ou produção para próprio consumo)"
}

codigo_para_descricao_contrato_trabalho = {
    1: "Sim, tem carteira de trabalho assinada",
    2: "Sim, é servidor público estatutário",
    3: "Não"
}


codigo_para_descricao_segmento_trabalho = {
    "01": "Agricultura, pecuária, produção florestal e pesca",
    "02": "Extração de petróleo, carvão mineral, minerais metálicos, pedra, areia, sal etc.",
    "03": "Indústria da transformação (inclusive confecção e fabricação caseira)",
    "04": "Fornecimento de eletricidade e gás, água, esgoto e coleta de lixo",
    "05": "Construção",
    "06": "Comércio no atacado e varejo",
    "07": "Reparação de veículos automotores e motocicletas",
    "08": "Transporte de passageiros",
    "09": "Transporte de mercadorias",
    "10": "Armazenamento, correios e serviços de entregas",
    "11": "Hospedagem (hotéis, pousadas etc.)",
    "12": "Serviço de alimentação (bares, restaurantes, ambulantes de alimentação)",
    "13": "Informação e comunicação (jornais, rádio e televisão, telecomunicações e informática)",
    "14": "Bancos, atividades financeiras e de seguros",
    "15": "Atividades imobiliárias",
    "16": "Escritórios de advocacia, engenharia, publicidade e veterinária (Atividades profissionais, científicas e técnicas)",
    "17": "Atividades de locação de mão de obra, segurança, limpeza, paisagismo e teleatendimento",
    "18": "Administração pública (governo federal, estadual e municipal)",
    "19": "Educação",
    "20": "Saúde humana e assistência social",
    "21": "Organizações religiosas, sindicatos e associações",
    "22": "Atividade artísticas, esportivas e de recreação",
    "23": "Cabeleireiros, tratamento de beleza e serviços pessoais",
    "24": "Serviço doméstico remunerado (será imputado da posição na ocupação)",
    "25": "Outro"
}

codigo_para_contato_funcionarios = {
   "01": "1 a 5 empregados ",
   "02": "6 a 10 empregados",
   "03": "11 ou mais empregados"


}

codigo_para_renda = {
    1: "Sim",
    2: "Não",
    3: "Não aplicável"

}

codigo_para_emprestmo = {
    1: "Sim, e pelo menos um morador conseguiu",
    2: "Sim, mas nenhum morador conseguiu",
    3: "Não solicitou"

}

codigo_para_descricao_domicilio = {
    "01": "Próprio - já pago ",
    "02": "Próprio - ainda pagando",
    "03": "Alugado",
    "04": "Cedido por empregador",
    "05": "Cedido por familiar",
    "06": "Cedido de outra forma ",
    "07": "Outra condição"
}

faixa_aluguel = {
    "00": "1 - 100",
    "01": "101 - 300",
    "02": "301 - 600",
    "03": "601 - 800",
    "04": "801 - 1.600",
    "05": "1.601 - 3.000",
    "06": "3.001 - 10.000",
    "07": "10.001 - 50.000",
    "08": "50.001 - 100.000",
    "09": "Mais de 100.000",
    "88": "Aluguel a vencer",
    None: "Não aplicável"  # Representa valores nulos
}

itens_basicos_protecao = {
    1: "Sim",
    2: "Não",
    3: "Não sabe"

}


# Carregar o arquivo CSV
df = pd.read_csv(r'C:\Users\monica\Downloads\base_covid_unificada.csv')

# Identificar colunas que começam com uma letra maiúscula e terminam com um número para excluir
colunas_para_excluir = [col for col in df.columns if re.match(r'^[A-Z].*\d$', col)]


######## AQUI COLOCAMOS AS COLUNAS PARA EXCLUIR ############################
colunas_para_excluir.extend([col for col in ['Semana no mês','Flag Rendimento recebido de aposentadoria e pensão','Função de trabalho','Flag afastado do trabalho', 'Motivo do afastamento',
'Tempo de afastamento ', 'Tem mais de um trabalho','Peso do domicílio e das pessoas (estratificado)','Domínios de projeção','Peso do domicílio e das pessoas','Projeção da população','Tipo de área','Região Metropolitana e Região Administrativa Integrada','B009D','B009C','Estrato', 'UPA','posest', 'Projeção da população', 'Peso do domícilio e das pessoas', 'Peso do domícilio e das pessoas (estratificado)', 'Número de ordem','C007A', 'C007F', 'C009A', 'C011A','C017A', 'Projeção da população'] if col in df.columns])

# Excluir as colunas identificadas do DataFrame
df.drop(columns=colunas_para_excluir, inplace=True)

# Aplicar o mapeamento nas colunas utilizando a variaveis do de para do dicionário criado
df['UF'] = df['UF'].map(uf_para_estado)

df['CAPITAL'] = df['CAPITAL'].map(uf_para_estado)

df['Situação do domicílio'] = df['Situação do domicílio'].map(situacao_domicilio)

df['Condição no domicílio'] = df['Condição no domicílio'].map(codigo_para_parentesco)

df['Cor ou raça'] = df['Cor ou raça'].map(codigo_para_raca)

df['Escolaridade'] = df['Escolaridade'].map(codigo_para_escolaridade)

df['Sexo'] = df['Sexo'].map(codigo_para_sexo)

df['Flag escola '] = df['Flag escola '].map(codigo_para_tipoEscola)

df['Flag Atividade Presencial'] = df['Flag Atividade Presencial'].map(codigo_para_formato_ensino)

df['Flag Atividade em casa'] = df['Flag Atividade em casa'].map(codigo_para_motivos_em_casa)

df['Flag realizou atividade'] = df['Flag realizou atividade'].map(codigo_para_motivos_nao_realizou)

df['Frequencia atividade escolar'] = df['Frequencia atividade escolar'].map(codigo_para_dias)

df['Tipo do teste (sanguineo)'] = df['Tipo do teste (sanguineo)'].map(codigo_para_descricao)

df['Flag restrição de  contato '] = df['Flag restrição de  contato '].map(codigo_para_restricao)

df['Flag  trabalho'] = df['Flag  trabalho'].map(codigo_para_descricao)


df['Papel no trabalho'] = df['Papel no trabalho'].map(codigo_para_descricao_papel_trabalho)

df['Contrato de trabalho'] = df['Contrato de trabalho'].map(codigo_para_descricao_contrato_trabalho)

df['Segmento de atuação'] = df['Segmento de atuação'].map(codigo_para_descricao_segmento_trabalho)

df['Contato com outros funcionarios'] = df['Contato com outros funcionarios'].map(codigo_para_contato_funcionarios)

df['Contribuição INSS'] = df['Contribuição INSS'].map(codigo_para_renda)

df['Valor aposentadoria/pensão'] = df['Valor aposentadoria/pensão'].map(codigo_para_renda)

df['Flag Bolsa família'] = df['Flag Bolsa família'].map(codigo_para_renda)

df['Auxílios emergenciais relacionados ao coronavirus'] = df['Auxílios emergenciais relacionados ao coronavirus'].map(codigo_para_renda)

df['Flag Seguro desemprego'] = df['Flag Seguro desemprego'].map(codigo_para_renda)

df['Flag Emprestimo periodo covid'] = df['Flag Emprestimo periodo covid'].map(codigo_para_emprestmo)

df['Emprestimo por banco ou financeira'] = df['Emprestimo por banco ou financeira'].map(codigo_para_renda)


df['Domicilio'] = df['Domicilio'].map(codigo_para_descricao_domicilio)

df['Número da faixa do aluguel pago'] = df['Número da faixa do aluguel pago'].map(faixa_aluguel)

df[' itens básicos de limpeza e proteção: sabão ou detergente'] = df[' itens básicos de limpeza e proteção: sabão ou detergente'].map(itens_basicos_protecao)

df['itens básicos de limpeza e proteção: álcool 70% ou superior (gel ou líquido)'] = df['itens básicos de limpeza e proteção: álcool 70% ou superior (gel ou líquido)'].map(itens_basicos_protecao)

df['itens básicos de limpeza e proteção: máscaras'] = df['itens básicos de limpeza e proteção: máscaras'].map(itens_basicos_protecao)



# Verificar se há valores nulos (códigos não mapeados)
# print("Valores nulos na coluna UF:", df['UF'].isnull().sum())

# Substituir valores nulos por 'Desconhecido' (opcional)
df['UF'].fillna('Desconhecido', inplace=True)

# print("Valores nulos na coluna CAPITAL:", df['CAPITAL'].isnull().sum())

# Substituir valores nulos por 'Desconhecido' (opcional)
df['CAPITAL'].fillna('Desconhecido', inplace=True)

# print("Valores nulos na coluna Situacao Domicilio", df['Situação do domicílio'].isnull().sum())

# Substituir valores nulos por 'Desconhecido' (opcional)
df['Situação do domicílio'].fillna('Desconhecido', inplace=True)


#### Laço for para iterar sobre as colunas
for coluna in colunas_para_mapear_sintomas:
    if coluna in df.columns:  # Verifica se a coluna existe no DataFrame
        df[coluna] = df[coluna].map(codigo_para_descricao)



for coluna in colunas_para_mapear_teste:
    if coluna in df.columns:  # Verifica se a coluna existe no DataFrame
        df[coluna] = df[coluna].map(codigo_para_descricao)


for coluna in colunas_para_mapear_teste_resultado:
    if coluna in df.columns:  # Verifica se a coluna existe no DataFrame
        df[coluna] = df[coluna].map(codigo_para_resultado)


for coluna in colunas_para_mapear_flag_teste:
    if coluna in df.columns:  # Verifica se a coluna existe no DataFrame
        df[coluna] = df[coluna].map(codigo_para_descricao)


#print(df)
#print(df.columns)


# Exportar o DataFrame para um arquivo CSV
df.to_csv(r'C:\Users\monica\Documents\projetoEinsten\Base_covid.csv', index=False)


Com a base exportada, realizamos o upload no Google Colab, onde vamos analisá-la e aplicar as etapas necessárias para explorar e interpretar os dados de forma mais detalhada.

In [8]:
import pandas as pd

# Ler o arquivo CSV como DataFrame
df = pd.read_csv('/content/Base_covid.csv', low_memory=False)


# Visualizar as primeiras linhas do DataFrame
display(df.head())


Ano         Mês        UF   CAPITAL  Número de seleção do domicílio  \
0  2020  2020-07-01  Rondônia  Rondônia                               1   
1  2020  2020-07-01  Rondônia  Rondônia                               1   
2  2020  2020-07-01  Rondônia  Rondônia                               1   
3  2020  2020-07-01  Rondônia  Rondônia                               1   
4  2020  2020-07-01  Rondônia  Rondônia                               2   

   Mês da pesquisa  Número da entrevista no domicílio Situação do domicílio  \
0                7                                  3                Urbana   
1                7                                  3                Urbana   
2                7                                  3                Urbana   
3                7                                  3                Urbana   
4                7                                  3                Urbana   

                         Condição no domicílio  Ano de nascimento  ...  \
0            Pessoa responsável pelo domicílio               1984  ...   
1  Cônjuge ou companheiro(a) de sexo diferente               1990  ...   
2         Filho(a) do responsável e do cônjuge               2006  ...   
3         Filho(a) do responsável e do cônjuge               2009  ...   
4            Pessoa responsável pelo domicílio               1963  ...   

   Somatório dos valores auxilio covid Flag Seguro desemprego  \
0                                  2.0                    NaN   
1                                  2.0                    NaN   
2                                  2.0                    NaN   
3                                  2.0                    NaN   
4                                  2.0                    NaN   

  Valor seguro desemprego Flag Emprestimo periodo covid  \
0                     3.0                           NaN   
1                     3.0                           NaN   
2                     3.0                           NaN   
3                     3.0                           NaN   
4                     3.0                           NaN   

   Emprestimo por banco ou financeira Domicilio  \
0                                 NaN       NaN   
1                                 NaN       NaN   
2                                 NaN       NaN   
3                                 NaN       NaN   
4                                 NaN       NaN   

  Número da faixa do aluguel pago  \
0                             NaN   
1                             NaN   
2                             NaN   
3                             NaN   
4                             NaN   

   itens básicos de limpeza e proteção: sabão ou detergente  \
0                                                Não          
1                                                Não          
2                                                Não          
3                                                Não          
4                                                Não          

  itens básicos de limpeza e proteção: álcool 70% ou superior (gel ou líquido)  \
0                                                Sim                             
1                                                Sim                             
2                                                Sim                             
3                                                Sim                             
4                                                Sim                             

  itens básicos de limpeza e proteção: máscaras  
0                                           Sim  
1                                           Sim  
2                                           Sim  
3                                           Sim  
4                                           Sim  

[5 rows x 83 columns]

In [ ]:
df.columns #verificando todas as colunas presentes no nosso DF que selecionamos

Index(['Ano', 'Mês', 'UF', 'CAPITAL', 'Número de seleção do domicílio',
       'Mês da pesquisa', 'Número da entrevista no domicílio',
       'Situação do domicílio', 'Condição no domicílio', 'Ano de nascimento',
       'Idade do morador ', 'Sexo', 'Cor ou raça', 'Escolaridade',
       'Frequenta escola', 'Flag escola ', 'Flag Atividade Presencial',
       'Flag Atividade em casa', 'Flag realizou atividade',
       'Frequencia atividade escolar', 'Flag febre', 'Flag tosse',
       'Flag dor de gaerganta', 'Flag problemas respiratórios',
       'Flag dor de cabeça', 'Flag dor no peito', 'Flag nausea',
       'Flag nariz escorrendo/entupido', 'Flag Fadiga', 'Flag dor nos olhos',
       'Flag perda de sentidos', 'Flag dor muscular', 'Flag diarreia',
       'Ida ao serviço de saúde', 'optou por ficar em casa',
       'Optou por ligar para um profissional', 'Optou pela auto medicação',
       'Seguiu a orientação profissional',
       'Optou por receber a visita de um profissional da saúde 

In [ ]:
# Obter valores únicos de uma variável (coluna)
valores_unicos = df['Mês'].unique()

# Exibir os valores únicos
print(valores_unicos)


['2020-07-01' '2020-09-01' '2020-08-01' '2020-11-01' '2020-10-01']


Instalando a biblioteca SQLITE3 para trabalhar com SQL junto ao Python

In [9]:
import sqlite3
import pandas as pd

# Criar conexão SQLite (salvo em disco)
conn = sqlite3.connect("database.sqlite")

# Salvar o DataFrame como tabela no SQLite
df.to_sql('base_covid', conn, if_exists='replace', index=False)

#Query para verificar número de linhas
query = "SELECT COUNT(*) AS total_linhas FROM base_covid"
result = pd.read_sql_query(query, conn)

# Exibir o resultado
print(result)

   total_linhas
0       1919883


In [ ]:
query = "SELECT DISTINCT Mês FROM base_covid"
result = pd.read_sql_query(query, conn)

# Exibir o resultado
print(result)


          Mês
0  2020-07-01
1  2020-09-01
2  2020-08-01
3  2020-11-01
4  2020-10-01


# **Questões para a Análise**

# Demografia e características dos moradores:

**A-** Qual é a distribuição de idade por estado e sexo?

**B-** Há uma diferença na renda média entre pessoas que buscaram atendimento em serviços públicos e privados por estado?

**C-** Qual é a proporção de pessoas que buscaram atendimento privado em relação ao público, segmentada por faixa de renda em cada estado?

**D-** A faixa de renda está correlacionada com a posse de itens básicos de limpeza e proteção (sabão, álcool 70% e máscaras)?

**E** Quantos moradores possuem mais de 60 anos em cada estado e qual a relação com a presença de comorbidades (ex.: diabetes, hipertensão)?

In [ ]:
# A- Qual é a distribuição de idade média por estado e sexo?
query = """
SELECT
    UF,
    SUM(COUNT(*)) OVER (PARTITION BY UF) AS total_pessoas_estado, -- Calcula o total de pessoas por estado somando os registros de todas as combinações de sexo para o mesmo estado.
    Sexo,
    COUNT(*) AS total_pessoas, -- Conta o número total de registros para cada combinação de estado e sexo
    AVG("Idade do morador ") AS idade_media
FROM base_covid
GROUP BY
    UF, Sexo - Agrupa os dados por estado (UF) e sexo (Sexo) para realizar os cálculos de contagem e média.
ORDER BY
    total_pessoas_estado DESC, UF, Sexo; -- Ordena os resultados pelo total geral de pessoas no estado em ordem decrescente
"""
result = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result)

UF  total_pessoas_estado    Sexo  total_pessoas  \
0          Minas Gerais                172725   Homem          83819   
1          Minas Gerais                172725  Mulher          88906   
2             São Paulo                167147   Homem          79628   
3             São Paulo                167147  Mulher          87519   
4        Rio de Janeiro                145417   Homem          67202   
5        Rio de Janeiro                145417  Mulher          78215   
6        Santa Catarina                117907   Homem          56787   
7        Santa Catarina                117907  Mulher          61120   
8     Rio Grande do Sul                111300   Homem          53604   
9     Rio Grande do Sul                111300  Mulher          57696   
10             Maranhão                100797   Homem          48479   
11             Maranhão                100797  Mulher          52318   
12               Paraná                100612   Homem          48692   
13               Paraná                100612  Mulher          51920   
14                Bahia                 85739   Homem          40747   
15                Bahia                 85739  Mulher          44992   
16                Ceará                 85395   Homem          40705   
17                Ceará                 85395  Mulher          44690   
18           Pernambuco                 83619   Homem          39449   
19           Pernambuco                 83619  Mulher          44170   
20       Espírito Santo                 78192   Homem          37632   
21       Espírito Santo                 78192  Mulher          40560   
22                Goiás                 69246   Homem          33466   
23                Goiás                 69246  Mulher          35780   
24                 Pará                 58847   Homem          28722   
25                 Pará                 58847  Mulher          30125   
26              Alagoas                 58227   Homem          27619   
27              Alagoas                 58227  Mulher          30608   
28          Mato Grosso                 57436   Homem          28289   
29          Mato Grosso                 57436  Mulher          29147   
30             Amazonas                 50977   Homem          25041   
31             Amazonas                 50977  Mulher          25936   
32              Paraíba                 49469   Homem          23323   
33              Paraíba                 49469  Mulher          26146   
34   Mato Grosso do Sul                 44185   Homem          21411   
35   Mato Grosso do Sul                 44185  Mulher          22774   
36                Piauí                 42229   Homem          20090   
37                Piauí                 42229  Mulher          22139   
38              Sergipe                 40746   Homem          19307   
39              Sergipe                 40746  Mulher          21439   
40  Rio Grande do Norte                 40486   Homem          19259   
41  Rio Grande do Norte                 40486  Mulher          21227   
42     Distrito Federal                 32929   Homem          15447   
43     Distrito Federal                 32929  Mulher          17482   
44                 Acre                 32032   Homem          15513   
45                 Acre                 32032  Mulher          16519   
46              Roraima                 27380   Homem          13518   
47              Roraima                 27380  Mulher          13862   
48             Rondônia                 27156   Homem          13325   
49             Rondônia                 27156  Mulher          13831   
50            Tocantins                 26126   Homem          13028   
51            Tocantins                 26126  Mulher          13098   
52                Amapá                 13562   Homem           6554   
53                Amapá                 13562  Mulher           7008   

    idade_media  
0     37.574166  
1     39.394214  
2     

**Distribuição de Idade por Estado e Sexo**
A análise revelou que:

**Estados com mais pessoas:**

Minas Gerais: 172.725 pessoas (idade média: homens 37,57 anos, mulheres 39,39 anos).

São Paulo: 167.147 pessoas (idade média: homens 37,95 anos, mulheres 40,14 anos).

Rio de Janeiro: 145.417 pessoas (idade média: homens 38,58 anos, mulheres 42,06 anos).

**Diferenças entre sexos:**

Em todos os estados, as mulheres superam os homens em número e têm idades médias mais altas.

**Maiores idades médias:**

Rio Grande do Sul e Rio de Janeiro destacam-se com idades médias acima de 42 anos para mulheres.

**Menores idades médias:**

Estados do Norte, como Roraima e Amapá, têm idades médias abaixo de 32 anos.
As regiões Sul e Sudeste apresentam populações mais numerosas e envelhecidas, enquanto a Região Norte é mais jovem e menos populosa.

In [10]:
query = """
SELECT DISTINCT "Renda "
FROM base_covid
ORDER BY "Renda " ASC;
"""

result = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result)


Renda 
0      NaN
1      0.0
2      1.0
3      2.0
4      3.0
5      4.0
6      5.0
7      6.0
8      7.0
9      8.0
10     9.0

In [49]:
# B- Há uma diferença na renda média entre pessoas que buscaram atendimento em serviços públicos e privados por estado?
query = """
WITH atendimento_classificado AS (
    SELECT
        UF,
        -- Classificação do tipo de atendimento entre privado ou público
        CASE
            WHEN "Local que buscou atendimento foi posto/UBS" = 'Sim'
              OR "Local que buscou atendimento foi pronto socorro do SUS/UPA" = 'Sim'
              OR "Local que buscou atendimento foi hospital do SUS" = 'Sim'
            THEN 'Público'
            WHEN "Local que buscou atendimento foi ambulatório ou consultório privado " = 'Sim'
              OR "Local que buscou atendimento foi pronto socorro privado" = 'Sim'
              OR "Local que buscou atendimento foi hospital privado" = 'Sim'
            THEN 'Privado'
            ELSE 'Não Informado'
        END AS tipo_atendimento,

        -- Fazendo o DE-PARA para transformar a variável renda nos valores reais
        CASE
            WHEN "Renda " = '00' THEN '0 - 100'
            WHEN "Renda " = '01' THEN '101 - 300'
            WHEN "Renda " = '02' THEN '301 - 600'
            WHEN "Renda " = '03' THEN '601 - 800'
            WHEN "Renda " = '04' THEN '801 - 1.600'
            WHEN "Renda " = '05' THEN '1.601 - 3.000'
            WHEN "Renda " = '06' THEN '3.001 - 10.000'
            WHEN "Renda " = '07' THEN '10.001 - 50.000'
            WHEN "Renda " = '08' THEN '50.001 - 100.000'
            WHEN "Renda " = '09' THEN 'Mais de 100.000'
            ELSE 'Não Aplicável'
        END AS faixa_renda,

        "Valor aposentadoria/pensão" AS aposentadoria,  -- Valor recebido de aposentadoria/pensão
        "Flag Bolsa família" AS recebe_bolsa_familia,  -- Se recebe Bolsa Família
        "Valor recebido ref bolsa família" AS valor_bolsa_familia -- Valor recebido do Bolsa Família
    FROM base_covid
    WHERE
        "Ida ao serviço de saúde" = 'Sim' -- Considera apenas pessoas que buscaram atendimento
)
SELECT
    UF,
    faixa_renda,  -- Faixa de renda convertida
    tipo_atendimento,
    COUNT(*) AS total_pacientes,
    aposentadoria,
    SUM(CASE WHEN recebe_bolsa_familia = 'Sim' THEN 1 ELSE 0 END) AS total_bolsa_familia,
    ROUND(AVG(valor_bolsa_familia), 2) AS media_valor_bolsa_familia
FROM atendimento_classificado
WHERE tipo_atendimento IN ('Público', 'Privado') -- Exclui "Não Informado"
GROUP BY UF, faixa_renda, tipo_atendimento
ORDER BY UF, faixa_renda, tipo_atendimento;

"""
result2 = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result2)

UF     faixa_renda tipo_atendimento  total_pacientes  \
0         Acre   1.601 - 3.000          Público                2   
1         Acre       101 - 300          Público                1   
2         Acre  3.001 - 10.000          Público                3   
3         Acre       601 - 800          Privado                1   
4         Acre     801 - 1.600          Público                8   
..         ...             ...              ...              ...   
310  Tocantins       601 - 800          Público                1   
311  Tocantins     801 - 1.600          Privado                1   
312  Tocantins     801 - 1.600          Público               10   
313  Tocantins   Não Aplicável          Privado               74   
314  Tocantins   Não Aplicável          Público               26   

    aposentadoria  total_bolsa_familia  media_valor_bolsa_familia  
0            None                    0                        NaN  
1            None                    0                        NaN  
2            None                    0                        NaN  
3            None                    0                        NaN  
4            None                    0                        NaN  
..            ...                  ...                        ...  
310          None                    0                        NaN  
311          None                    0                        NaN  
312          None                    0                        NaN  
313           Não                    0                       1.82  
314          None                    3                     239.67  

[315 rows x 7 columns]

In [52]:
#C- Qual é a proporção de pessoas que buscaram atendimento privado em relação ao público, segmentada por faixa de renda em cada estado?

query = """
WITH faixa_renda AS (
    SELECT
        UF,  -- Estado
        -- Conversão dos códigos de renda para faixas reais
        CASE
            WHEN "Renda " = '00' THEN '0 - 100'
            WHEN "Renda " = '01' THEN '101 - 300'
            WHEN "Renda " = '02' THEN '301 - 600'
            WHEN "Renda " = '03' THEN '601 - 800'
            WHEN "Renda " = '04' THEN '801 - 1.600'
            WHEN "Renda " = '05' THEN '1.601 - 3.000'
            WHEN "Renda " = '06' THEN '3.001 - 10.000'
            WHEN "Renda " = '07' THEN '10.001 - 50.000'
            WHEN "Renda " = '08' THEN '50.001 - 100.000'
            WHEN "Renda " = '09' THEN 'Mais de 100.000'
            ELSE 'Não Aplicável'
        END AS faixa_renda,  -- Segmentação por faixa de renda

        COUNT(*) AS total_pessoas,  -- Total de pessoas por faixa de renda e estado

        -- Contagem de pessoas que buscaram atendimento privado
        SUM(CASE WHEN
            "Local que buscou atendimento foi ambulatório ou consultório privado " = 'Sim' OR
            "Local que buscou atendimento foi pronto socorro privado" = 'Sim' OR
            "Local que buscou atendimento foi hospital privado" = 'Sim'
            THEN 1 ELSE 0 END) AS total_atendimento_privado,

        -- Contagem de pessoas que buscaram atendimento público
        SUM(CASE WHEN
            "Local que buscou atendimento foi posto/UBS" = 'Sim' OR
            "Local que buscou atendimento foi pronto socorro do SUS/UPA" = 'Sim' OR
            "Local que buscou atendimento foi hospital do SUS" = 'Sim'
            THEN 1 ELSE 0 END) AS total_atendimento_publico

    FROM base_covid
    WHERE
        "Renda " IS NOT NULL -- Garante que os registros de renda sejam válidos
    GROUP BY UF, faixa_renda
),
proporcao_atendimento AS (
    SELECT
        UF,
        faixa_renda,
        total_pessoas,
        total_atendimento_publico,
        total_atendimento_privado,

        -- Cálculo do percentual de atendimento privado e público
        ROUND(total_atendimento_privado * 100.0 / NULLIF(total_atendimento_publico + total_atendimento_privado, 0), 2) AS percentual_privado,
        ROUND(total_atendimento_publico * 100.0 / NULLIF(total_atendimento_publico + total_atendimento_privado, 0), 2) AS percentual_publico
    FROM faixa_renda
)
SELECT * FROM proporcao_atendimento
ORDER BY UF, faixa_renda;

"""
result3 = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result3)

UF      faixa_renda  total_pessoas  total_atendimento_publico  \
0         Acre          0 - 100             20                          0   
1         Acre    1.601 - 3.000            425                          2   
2         Acre  10.001 - 50.000             24                          0   
3         Acre        101 - 300             54                          1   
4         Acre   3.001 - 10.000            241                          3   
..         ...              ...            ...                        ...   
224  Tocantins        101 - 300             81                          0   
225  Tocantins   3.001 - 10.000            214                          1   
226  Tocantins        301 - 600            146                          2   
227  Tocantins        601 - 800             97                          1   
228  Tocantins      801 - 1.600            937                         10   

     total_atendimento_privado  percentual_privado  percentual_publico  
0                            0                 NaN                 NaN  
1                            0                0.00              100.00  
2                            0                 NaN                 NaN  
3                            0                0.00              100.00  
4                            0                0.00              100.00  
..                         ...                 ...                 ...  
224                          0                 NaN                 NaN  
225                          1               50.00               50.00  
226                          0                0.00              100.00  
227                          1               50.00               50.00  
228                          5               33.33               66.67  

[229 rows x 7 columns]

In [54]:
#D- A faixa de renda está correlacionada com a posse de itens básicos de limpeza e proteção (sabão, álcool 70% e máscaras)?

query = """
-- Correlação entre faixa de renda e posse de itens básicos de limpeza e proteção
-- Correlação entre faixa de renda, posse de itens básicos e total de pessoas
SELECT
    "Mês", -- Mês da análise
    CASE
        WHEN "Renda " = '00' THEN '0 - 100'
        WHEN "Renda " = '01' THEN '101 - 300'
        WHEN "Renda " = '02' THEN '301 - 600'
        WHEN "Renda " = '03' THEN '601 - 800'
        WHEN "Renda " = '04' THEN '801 - 1.600'
        WHEN "Renda " = '05' THEN '1.601 - 3.000'
        WHEN "Renda " = '06' THEN '3.001 - 10.000'
        WHEN "Renda " = '07' THEN '10.001 - 50.000'
        WHEN "Renda " = '08' THEN '50.001 - 100.000'
        WHEN "Renda " = '09' THEN 'Mais de 100.000'
        ELSE 'Não Aplicável'
    END AS faixa_renda, -- Segmentação por faixa de renda

    COUNT(*) AS total_domicilios, -- Total de domicílios por faixa de renda
    SUM("Número de seleção do domicílio") AS total_pessoas, -- Total de pessoas (soma da variável que representa pessoas por domicílio)
    SUM(CASE WHEN " itens básicos de limpeza e proteção: sabão ou detergente" = 'Sim' THEN 1 ELSE 0 END) AS total_sabao, -- Total com sabão/detergente
    SUM(CASE WHEN "itens básicos de limpeza e proteção: álcool 70% ou superior (gel ou líquido)" = 'Sim' THEN 1 ELSE 0 END) AS total_alcool, -- Total com álcool 70%
    SUM(CASE WHEN "itens básicos de limpeza e proteção: máscaras" = 'Sim' THEN 1 ELSE 0 END) AS total_mascaras -- Total com máscaras

FROM
    base_covid
GROUP BY
    "Mês", "Renda " -- Agrupar por mês e faixa de renda
ORDER BY
    "Mês" ASC, "Renda " ASC; -- Ordenar por mês e faixa de renda



"""
result4 = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result4)

Mês       faixa_renda  total_domicilios  total_pessoas  \
0   2020-07-01     Não Aplicável            382694        2862486   
1   2020-07-01           0 - 100               149           1180   
2   2020-07-01         101 - 300               440           3331   
3   2020-07-01         301 - 600               303           2204   
4   2020-07-01         601 - 800                79            578   
5   2020-07-01       801 - 1.600               317           2231   
6   2020-07-01     1.601 - 3.000                99            696   
7   2020-07-01    3.001 - 10.000                75            543   
8   2020-07-01   10.001 - 50.000                10             87   
9   2020-08-01     Não Aplicável            385111        2880330   
10  2020-08-01           0 - 100               164           1298   
11  2020-08-01         101 - 300               413           2975   
12  2020-08-01         301 - 600               294           2255   
13  2020-08-01         601 - 800                78            582   
14  2020-08-01       801 - 1.600               285           2088   
15  2020-08-01     1.601 - 3.000                94            683   
16  2020-08-01    3.001 - 10.000                76            514   
17  2020-08-01   10.001 - 50.000                 5             38   
18  2020-09-01     Não Aplicável            385878        2886759   
19  2020-09-01           0 - 100               171           1309   
20  2020-09-01         101 - 300               425           3037   
21  2020-09-01         301 - 600               287           2211   
22  2020-09-01         601 - 800                73            564   
23  2020-09-01       801 - 1.600               280           2070   
24  2020-09-01     1.601 - 3.000                97            673   
25  2020-09-01    3.001 - 10.000                80            565   
26  2020-09-01   10.001 - 50.000                 7             52   
27  2020-10-01     Não Aplicável            379100        2833432   
28  2020-10-01           0 - 100               128            985   
29  2020-10-01         101 - 300               397           2888   
30  2020-10-01         301 - 600               293           2298   
31  2020-10-01         601 - 800                83            600   
32  2020-10-01       801 - 1.600               270           1969   
33  2020-10-01     1.601 - 3.000               105            753   
34  2020-10-01    3.001 - 10.000                78            558   
35  2020-10-01   10.001 - 50.000                 7             52   
36  2020-11-01     Não Aplicável            240053        1794977   
37  2020-11-01           0 - 100               883           6682   
38  2020-11-01         101 - 300              4701          35585   
39  2020-11-01         301 - 600             10227          76411   
40  2020-11-01         601 - 800              5608          42073   
41  2020-11-01       801 - 1.600             63765         475620   
42  2020-11-01     1.601 - 3.000             34415         256972   
43  2020-11-01    3.001 - 10.000             19256         145193   
44  2020-11-01   10.001 - 50.000              2513          18657   
45  2020-11-01  50.001 - 100.000                13            100   
46  2020-11-01   Mais de 100.000                 4             33   

    total_sabao  total_alcool  total_mascaras  
0        155690        375066          363671  
1            45           145             142  
2           138           431             416  
3           108           296             280  
4            22            76              75  
5           134           314             298  
6            49            97              96  
7            40            75              73  
8             6            10              10  
9        153242        379168          365475  
10           49           161             154  
11          118           404             386  
12          110           293             268  
13           26           

**Faixa de renda "0 - 100" tem menor cobertura:**

Essa faixa de renda representa um número muito pequeno de domicílios em relação às outras, com registros significativamente baixos.
Possível implicação:
Famílias de baixa renda têm menor acesso a esses itens.
Dados dessa faixa podem ser incompletos ou pouco representativos.
Faixas de renda mais altas apresentam maior acesso:

Faixas como "801 - 1.600", "1.601 - 3.000", e "3.001 - 10.000" mostram altos totais de sabão, álcool 70% e máscaras.

Mesmo faixas superiores, como "10.001 - 50.000", mantêm altos valores totais indicando que pessoas de maior renda têm melhor acesso embora que menos pessoas nessa faixa salarial.

In [56]:
#E - Quantos moradores possuem mais de 60 anos em cada estado e qual a relação com a presença de comorbidades (ex.: diabetes, hipertensão)?

query = """
WITH idosos_por_estado AS (
    SELECT
        UF,  -- Estado
        COUNT(*) AS total_idosos  -- Total de moradores com >60 anos
    FROM
        base_covid
    WHERE
        "Idade do morador" > 60  -- Filtra moradores com > 60 anos
    GROUP BY
        UF
),
idosos_comorbidades AS (
    SELECT
        UF,  -- Estado
        SUM(CASE WHEN "Flag diabete" = 'Sim'
                 OR "Flag hipertensão" = 'Sim'
                 OR "Flag doenças respiratórias" = 'Sim'
                 OR "Flag doenças cardiovasculares" = 'Sim'
                 OR "Flag doenças cancerigenas" = 'Sim'
                 THEN 1 ELSE 0 END) AS total_comorbidades,  -- Total de idosos com pelo menos uma comorbidade
        SUM(CASE WHEN "Flag diabete" = 'Sim' THEN 1 ELSE 0 END) AS total_diabetes,  -- Total de idosos com diabetes
        SUM(CASE WHEN "Flag hipertensão" = 'Sim' THEN 1 ELSE 0 END) AS total_hipertensao,  -- Total de idosos com hipertensão
        SUM(CASE WHEN "Flag diabete" != 'Sim'
                 AND "Flag hipertensão" != 'Sim'
                 AND "Flag doenças respiratórias" != 'Sim'
                 AND "Flag doenças cardiovasculares" != 'Sim'
                 AND "Flag doenças cancerigenas" != 'Sim'
                 THEN 1 ELSE 0 END) AS total_sem_comorbidades  -- Total de idosos sem nenhuma comorbidade
    FROM
        base_covid
    WHERE
        "Idade do morador" > 60  -- Filtra apenas os idosos
    GROUP BY
        UF
)
SELECT
    ipe.UF,  -- Estado
    ipe.total_idosos,  -- Total de idosos no estado
    ic.total_comorbidades,  -- Total de idosos com pelo menos uma comorbidade
    ic.total_diabetes,  -- Total de idosos com diabetes
    ic.total_hipertensao,  -- Total de idosos com hipertensão
    ic.total_sem_comorbidades  -- Total de idosos sem nenhuma comorbidade
FROM
    idosos_por_estado ipe
LEFT JOIN
    idosos_comorbidades ic
    ON ipe.UF = ic.UF  -- Junta os dados de idosos e comorbidades por estado
ORDER BY
    ipe.total_idosos DESC;  -- Ordena pelos estados com mais idosos

"""
result5= pd.read_sql_query(query, conn)

# Exibir o resultado
display(result5)

UF  total_idosos  total_comorbidades  total_diabetes  \
0          Minas Gerais        172725               30228            6810   
1             São Paulo        167147               27289            7189   
2        Rio de Janeiro        145417               23482            5074   
3        Santa Catarina        117907               17564            4944   
4     Rio Grande do Sul        111300               21965            5508   
5              Maranhão        100797               12800            2173   
6                Paraná        100612               16057            4277   
7                 Bahia         85739               11515            2829   
8                 Ceará         85395               12002            2402   
9            Pernambuco         83619               11567            2261   
10       Espírito Santo         78192               11633            2839   
11                Goiás         69246               11449            2702   
12                 Pará         58847                9290            1329   
13              Alagoas         58227                7435            1541   
14          Mato Grosso         57436                7463            1751   
15             Amazonas         50977                5674             840   
16              Paraíba         49469                7486            1642   
17   Mato Grosso do Sul         44185                5919            1535   
18                Piauí         42229                5445            1419   
19              Sergipe         40746                5537            1208   
20  Rio Grande do Norte         40486                6480            1468   
21     Distrito Federal         32929                5416            1277   
22                 Acre         32032                3786             635   
23              Roraima         27380                2796             396   
24             Rondônia         27156                3236             801   
25            Tocantins         26126                3505             729   
26                Amapá         13562                1933             246   

    total_hipertensao  total_sem_comorbidades  
0               12592                   63248  
1               10049                   61120  
2                7483                   63076  
3                7199                   42611  
4                9921                   36460  
5                3419                   45516  
6                7027                   34811  
7                4207                   35079  
8                3953                   36109  
9                4010                   35032  
10               4259                   29304  
11               4176                   25291  
12               1945                   24545  
13               2436                   27124  
14               2611                   20540  
15               1116                   23046  
16               2516                   21085  
17               2542                   15706  
18               2128                   16778  
19               2041                   17013  
20               2210                   16010  
21               1874                   12421  
22               1110                   13708  
23                638                   12892  
24               1202                   10919  
25               1161                   10240  
26                342                    5645

**Conclusão**

Os estados mais populosos, como Minas Gerais, São Paulo e Rio de Janeiro, concentram tanto o maior número de idosos quanto os maiores números de comorbidades. Por outro lado, estados menores, como Amapá e Roraima, apresentam números muito inferiores, refletindo suas populações menores. Este tipo de análise é essencial para planejar políticas públicas voltadas para a saúde da população idosa.

# Questões Saúde e sintomas:

**F-** Qual a frequência dos principais sintomas reportados (ex.: febre, tosse, perda de sentidos) por mês?

**G-** Qual é a relação entre moradores que buscaram atendimento médico e os sintomas relatados?

**H-** Qual o percentual de moradores que realizaram testes de COVID-19 e o resultado desses testes (cotonete e sanguíneo)?

**I-** Qual o percentual de moradores que NÂO realizaram testes de COVID-19 e o resultado desses testes (cotonete e sanguíneo)?

In [58]:
#F- Qual a frequência dos principais sintomas reportados (ex.: febre, tosse, perda de sentidos) por mês?

query = """
WITH sintomas_por_mes AS (
    SELECT
        "Mês",  -- Mês do ano
        SUM(CASE WHEN "Flag febre" = 'Sim' THEN 1 ELSE 0 END) AS febre,  -- Total de casos com febre
        SUM(CASE WHEN "Flag tosse" = 'Sim' THEN 1 ELSE 0 END) AS tosse,  -- Total de casos com tosse
        SUM(CASE WHEN "Flag perda de sentidos" = 'Sim' THEN 1 ELSE 0 END) AS perda_de_sentidos,  -- Total de casos com perda de sentidos
        SUM(  -- Soma de todos os sintomas reportados
            CASE WHEN "Flag febre" = 'Sim' THEN 1 ELSE 0 END +
            CASE WHEN "Flag tosse" = 'Sim' THEN 1 ELSE 0 END +
            CASE WHEN "Flag perda de sentidos" = 'Sim' THEN 1 ELSE 0 END
        ) AS total_sintomas
    FROM
        base_covid
    GROUP BY
        "Mês"  -- Agrupa os resultados por mês
    ORDER BY
        "Mês" DESC  -- Ordena os resultados por mês
)
SELECT
    "Mês",
    febre,
    tosse,
    perda_de_sentidos,
    total_sintomas  -- Soma total de sintomas reportados por mês
FROM
    sintomas_por_mes;

"""
result6 = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result6)

Mês  febre  tosse  perda_de_sentidos  total_sintomas
0  2020-11-01   3168   5259               1467            9894
1  2020-10-01   1441   5802               3660           10903
2  2020-09-01   1820   7212               4107           13139
3  2020-08-01   2548   9783               5312           17643
4  2020-07-01   3042  11553               5761           20356

**Conclusões:**

Tosse foi o sintoma mais prevalente em todos os meses analisados, com um pico em julho de 2020 (11.553 casos).

Febre e perda de sentidos também tiveram seus maiores números em julho de 2020, indicando um pico geral nos sintomas.

A redução nos números de sintomas ao longo do tempo pode refletir o impacto das medidas de saúde pública ou uma possível diminuição na disseminação do vírus durante este período.

In [ ]:
query = """
SELECT DISTINCT "Ida ao serviço de saúde",
                 "Optou por ligar para um profissional",
                 "Optou por receber a visita de um profissional da saúde SUS",
                 "Optou por receber a visita de um profissional da saúde PARTICULAR"
                 FROM base_covid;
"""
result = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result)

Ida ao serviço de saúde Optou por ligar para um profissional  \
0                     None                                 None   
1                     None                                 None   
2                      Sim                                  Não   
3                     None                                 None   
4                      Não                                  Não   
5                     None                                 None   
6                     None                                 None   
7                      Sim                                  Sim   
8                      Sim                             Ignorado   
9                      Não                                  Sim   
10                Ignorado                             Ignorado   
11                    None                                 None   
12                    None                                 None   
13                Ignorado                                  Não   
14                    None                                 None   
15                    None                                 None   
16                     Não                             Ignorado   
17                Ignorado                                  Sim   
18                    None                                 None   
19                     Não                                  Não   
20                     Sim                                 None   
21                     Não                                  Sim   
22                     Não                                  Não   
23                     Não                                  Não   
24                     Não                             Ignorado   
25                     Não                                  Sim   
26                     Não                             Ignorado   
27                     Não                             Ignorado   
28                     Não                                  Sim   
29                     Não                                  Não   
30                Ignorado                                 None   
31                     Não                                  Sim   
32                     Não                                  Sim   
33                     Não                                  Não   

   Optou por receber a visita de um profissional da saúde SUS  \
0                                                None           
1                                                 Sim           
2                                                None           
3                                                 Sim           
4                                                None           
5                                                 Não           
6                                                 Não           
7                                                None           
8                                                None           
9                                                None           
10                                               None           
11                                                Sim           
12                                           Ignorado           
13                                               None           
14                                           Ignorado           
15                                                Não           
16                                               None           
17                                               None           
18                                           Ignorado           
19                                                Não           
20                                               None           
21                                                Não           
22                                                Não           
23                                                Sim           
24                              

In [61]:
#G- Qual é a relação entre moradores que buscaram atendimento médico e os sintomas relatados?

query = """
WITH moradores_atendimento AS (
    SELECT Mês,
        CASE
            WHEN "Ida ao serviço de saúde" = 'Sim' OR
                 "Optou por ligar para um profissional" = 'Sim' OR
                 "Optou por receber a visita de um profissional da saúde SUS" = 'Sim' OR
                 "Optou por receber a visita de um profissional da saúde PARTICULAR" = 'Sim'
            THEN 'Sim'
            ELSE 'Não'
        END AS buscou_atendimento,  -- Flag combinada para busca de atendimento
        SUM(CASE WHEN "Flag febre" = 'Sim' THEN 1 ELSE 0 END) AS febre,  -- Total de casos com febre
        SUM(CASE WHEN "Flag tosse" = 'Sim' THEN 1 ELSE 0 END) AS tosse,  -- Total de casos com tosse
        SUM(CASE WHEN "Flag perda de sentidos" = 'Sim' THEN 1 ELSE 0 END) AS perda_de_sentidos,  -- Total de casos com perda de sentidos
        COUNT(*) AS total_pessoas  -- Total de moradores no grupo
    FROM
        base_covid
    WHERE
        "Ida ao serviço de saúde" IN ('Sim', 'Não') OR
        "Optou por ligar para um profissional" IN ('Sim', 'Não') OR
        "Optou por receber a visita de um profissional da saúde SUS" IN ('Sim', 'Não') OR
        "Optou por receber a visita de um profissional da saúde PARTICULAR" IN ('Sim', 'Não')  -- Garante que as variáveis sejam válidas
    GROUP BY
        buscou_atendimento, Mês  -- Agrupa pelo indicador de busca por atendimento
)
SELECT
    Mês,
    buscou_atendimento,  -- Indicador de busca por atendimento médico
    febre,
    tosse,
    perda_de_sentidos,
    total_pessoas
FROM
    moradores_atendimento
    WHERE buscou_atendimento = 'Sim'
    ORDER BY Mês DESC;

"""
result7 = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result7)

Mês buscou_atendimento  febre  tosse  perda_de_sentidos  \
0  2020-11-01                Sim   1861   2163                938   
1  2020-10-01                Sim    889   4191               2374   
2  2020-09-01                Sim   1120   5127               2717   
3  2020-08-01                Sim   1571   6918               3514   
4  2020-07-01                Sim   1903   8170               3806   

   total_pessoas  
0           4562  
1           8809  
2          10504  
3          14162  
4          15828

In [63]:

query = """
WITH moradores_atendimento AS (
    SELECT Mês,
        CASE
            WHEN "Ida ao serviço de saúde" = 'Sim' OR
                 "Optou por ligar para um profissional" = 'Sim' OR
                 "Optou por receber a visita de um profissional da saúde SUS" = 'Sim' OR
                 "Optou por receber a visita de um profissional da saúde PARTICULAR" = 'Sim'
            THEN 'Sim'
            ELSE 'Não'
        END AS buscou_atendimento,  -- Flag combinada para busca de atendimento
        SUM(CASE WHEN "Flag febre" = 'Sim' THEN 1 ELSE 0 END) AS febre,  -- Total de casos com febre
        SUM(CASE WHEN "Flag tosse" = 'Sim' THEN 1 ELSE 0 END) AS tosse,  -- Total de casos com tosse
        SUM(CASE WHEN "Flag perda de sentidos" = 'Sim' THEN 1 ELSE 0 END) AS perda_de_sentidos,  -- Total de casos com perda de sentidos
        COUNT(*) AS total_pessoas  -- Total de moradores no grupo
    FROM
        base_covid
    WHERE
        "Ida ao serviço de saúde" IN ('Sim', 'Não') OR
        "Optou por ligar para um profissional" IN ('Sim', 'Não') OR
        "Optou por receber a visita de um profissional da saúde SUS" IN ('Sim', 'Não') OR
        "Optou por receber a visita de um profissional da saúde PARTICULAR" IN ('Sim', 'Não')  -- Garante que as variáveis sejam válidas
    GROUP BY
        buscou_atendimento, Mês  -- Agrupa pelo indicador de busca por atendimento
)
SELECT
    Mês,
    buscou_atendimento,  -- Indicador de busca por atendimento médico
    febre,
    tosse,
    perda_de_sentidos,
    total_pessoas
FROM
    moradores_atendimento
    WHERE buscou_atendimento = 'Não'
    ORDER BY Mês DESC;

"""
result8 = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result8)

Mês buscou_atendimento  febre  tosse  perda_de_sentidos  \
0  2020-11-01                Não   1306   3096                528   
1  2020-10-01                Não    547   1587               1272   
2  2020-09-01                Não    694   2061               1368   
3  2020-08-01                Não    958   2841               1780   
4  2020-07-01                Não   1129   3363               1937   

   total_pessoas  
0           9563  
1           5087  
2           6302  
3           8342  
4           9548

**Comparação Resumida: Quem buscou vs. Quem não buscou atendimento médico**

1. Frequência Total de Pessoas
Buscou atendimento: Maior número de pessoas em todos os meses.
Exemplo: Julho/2020 – 15.828 pessoas (Sim) vs. 9.548 pessoas (Não).

2. Sintomas Relatados
Febre: Relatada mais frequentemente por quem buscou atendimento.
Exemplo: Julho/2020 – 1.903 (Sim) vs. 1.129 (Não).

Tosse: Sintoma mais comum nos dois grupos.

Exemplo: Julho/2020 – 8.170 (Sim) vs. 3.363 (Não).

Perda de Sentidos: Também mais frequente no grupo "Sim".

Exemplo: Agosto/2020 – 3.514 (Sim) vs. 1.780 (Não).


**Conclusão**
Moradores com sintomas mais graves/múltiplos têm maior probabilidade de buscar atendimento.
Tosse foi o sintoma mais comum em ambos os grupos.
O pico geral ocorreu em julho/2020, refletindo um momento crítico da pandemia.

In [65]:
#H- Qual o percentual de moradores que realizaram testes de COVID-19 e o resultado desses testes (cotonete e sanguíneo)?

query = """
WITH total_moradores AS (
    SELECT
        COUNT(*) AS total_geral --Selecionando o total de pessoas
    FROM
        base_covid
),
testes_covid AS (
    SELECT
        Mês, -- Extrai o mês e ano da data
        CASE
            WHEN "Tipo do teste (cotonete)" = 'Sim' THEN 'Teste Cotonete'
            WHEN "Tipo do teste (sanguineo)" = 'Sim' THEN 'Teste Sanguíneo'
            ELSE 'Nenhum Teste'
        END AS tipo_teste, -- Classifica os 2 tipos de teste
        CASE
            WHEN "Tipo do teste (cotonete)" = 'Sim' THEN "Flag resultado teste covid (cotonete)"
            WHEN "Tipo do teste (sanguineo)" = 'Sim' THEN "Flag resultado teste covid (sanguineo)"
            ELSE 'Não Realizado'
        END AS resultado_teste, -- Classifica os resultados com base no tipo
        COUNT(*) AS total_testados
    FROM
        base_covid
    WHERE
        "Flag teste covid" = 'Sim' -- Considera apenas quem realizou teste
        AND (
            "Tipo do teste (cotonete)" = 'Sim' OR "Tipo do teste (sanguineo)" = 'Sim'
        ) -- Garante que seja cotonete ou sanguíneo
    GROUP BY
        Mês, tipo_teste, resultado_teste
)
SELECT
    Mês,
    tipo_teste,
    resultado_teste,
    total_testados,
    ROUND(total_testados * 100.0 / tm.total_geral, 2) AS percentual_total -- Percentual em relação ao total de moradores
FROM
    testes_covid tc
CROSS JOIN
    total_moradores tm -- Combina o total geral para cada linha
ORDER BY
    Mês DESC, total_testados DESC;
"""
result9 = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result9)

Mês       tipo_teste                resultado_teste  \
0   2020-11-01   Teste Cotonete                       Negativo   
1   2020-11-01  Teste Sanguíneo                       Negativo   
2   2020-11-01   Teste Cotonete                       Positivo   
3   2020-11-01  Teste Sanguíneo                       Positivo   
4   2020-11-01   Teste Cotonete  Ainda não recebeu o resultado   
5   2020-11-01  Teste Sanguíneo  Ainda não recebeu o resultado   
6   2020-11-01   Teste Cotonete                   Inconclusivo   
7   2020-11-01  Teste Sanguíneo                   Inconclusivo   
8   2020-11-01   Teste Cotonete                       Ignorado   
9   2020-11-01  Teste Sanguíneo                       Ignorado   
10  2020-10-01   Teste Cotonete                       Negativo   
11  2020-10-01  Teste Sanguíneo                       Negativo   
12  2020-10-01   Teste Cotonete                       Positivo   
13  2020-10-01  Teste Sanguíneo                       Positivo   
14  2020-09-01   Teste Cotonete                       Negativo   
15  2020-09-01  Teste Sanguíneo                       Negativo   
16  2020-09-01   Teste Cotonete                       Positivo   
17  2020-09-01  Teste Sanguíneo                       Positivo   
18  2020-09-01   Teste Cotonete                       Ignorado   
19  2020-09-01  Teste Sanguíneo                       Ignorado   
20  2020-08-01   Teste Cotonete                       Negativo   
21  2020-08-01  Teste Sanguíneo                       Negativo   
22  2020-08-01   Teste Cotonete                       Positivo   
23  2020-08-01  Teste Sanguíneo                       Positivo   
24  2020-08-01   Teste Cotonete                       Ignorado   
25  2020-07-01   Teste Cotonete                       Negativo   
26  2020-07-01  Teste Sanguíneo                       Negativo   
27  2020-07-01   Teste Cotonete                       Positivo   
28  2020-07-01  Teste Sanguíneo                       Positivo   
29  2020-07-01   Teste Cotonete                       Ignorado   
30  2020-07-01  Teste Sanguíneo                       Ignorado   

    total_testados  percentual_total  
0            13564              0.71  
1             7876              0.41  
2             5789              0.30  
3             3018              0.16  
4              594              0.03  
5              139              0.01  
6              104              0.01  
7               44              0.00  
8                5              0.00  
9                4              0.00  
10            3548              0.18  
11            2790              0.15  
12             627              0.03  
13             255              0.01  
14            3142              0.16  
15            2430              0.13  
16             564              0.03  
17             220              0.01  
18               1              0.00  
19               1              0.00  
20            2562              0.13  
21            1864              0.10  
22             463              0.02  
23             183              0.01  
24               2              0.00  
25            1791              0.09  
26            1410              0.07  
27             406              0.02  
28             161              0.01  
29               4              0.00  
30               2              0.00

**Conclusões:**

Testes negativos predominam em todos os meses analisados, enquanto os positivos são uma fração significativa.

O teste de cotonete foi mais amplamente utilizado do que o teste sanguíneo.
Resultados não recebidos, inconclusivos ou ignorados representam uma pequena parte, indicando um processo de testagem relativamente eficaz.

A análise sugere que o pico de testagens ocorreu em novembro de 2020, seguido por uma queda nos meses anteriores.

In [ ]:
#I- Qual o percentual de moradores que NÂO realizaram testes de COVID-19 e o resultado desses testes (cotonete e sanguíneo)?

query = """
WITH total_moradores AS (
    SELECT
        COUNT(*) AS total_geral -- Selecionando o total de pessoas
    FROM
        base_covid
),
nao_testaram AS (
    SELECT
        Mês, -- Extrai o mês e ano, se aplicável
        'Não Testou' AS tipo_teste, -- Classifica todos como "Não Testou"
        'Sem Resultado' AS resultado_teste, -- Não há resultado para quem não testou
        COUNT(*) AS total_testados -- Total de moradores que não testaram
    FROM
        base_covid
    WHERE
        "Flag teste covid" IN ('Não', 'Ignorado') -- Considera apenas quem não realizou teste
    GROUP BY
        Mês
)
SELECT
    Mês,
    tipo_teste,
    resultado_teste,
    total_testados,
    ROUND(total_testados * 100.0 / tm.total_geral, 2) AS percentual_total -- Percentual em relação ao total de moradores
FROM
    nao_testaram nt
CROSS JOIN
    total_moradores tm -- Combina o total geral para cada linha
ORDER BY
    Mês DESC, total_testados DESC;
"""
result = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result)

Mês  tipo_teste resultado_teste  total_testados  percentual_total
0  2020-11-01  Não Testou   Sem Resultado          331568             17.27
1  2020-10-01  Não Testou   Sem Resultado           23440              1.22
2  2020-09-01  Não Testou   Sem Resultado           20394              1.06
3  2020-08-01  Não Testou   Sem Resultado           16682              0.87
4  2020-07-01  Não Testou   Sem Resultado           11840              0.62

**Conclusões:**

Elevado percentual em novembro de 2020: Isso sugere que, apesar de um número expressivo de pessoas realizando testes, ainda havia uma grande parcela da população que não tinha acesso ou optava por não realizar o procedimento.

Tendência de redução nos meses anteriores: **Indica possíveis melhorias na disseminação de informações e aumento da capacidade de testagem.**

Impacto: A análise desses dados é fundamental para entender lacunas na testagem e implementar estratégias para alcançar populações que não foram testadas.

# Relacionando sintomas às comorbidades da população:

 J-Há uma correlação entre comorbidades (ex.: diabetes, hipertensão) e a ocorrência de sintomas?

 K-Quais estados têm maior frequência de sintomas em pessoas com comorbidades?

L- Há uma diferença no tipo de serviço de saúde procurado (público ou privado) por pessoas com comorbidades e sintomas?

M-Pessoas com comorbidades realizaram mais testes de COVID-19 em relação às que não possuem comorbidades?

N- Entre aqueles que testaram positivo para COVID-19, qual é a frequência de comorbidades e sintomas?

O- Pessoas com comorbidades (ex.: diabetes, hipertensão) são mais propensas a buscar atendimento médico ao apresentar sintomas?

In [ ]:
#J-Há uma correlação entre comorbidades (ex.: diabetes, hipertensão) e a ocorrência de sintomas?

query = """
WITH comorbidades_sintomas AS (
    SELECT
        CASE
            WHEN "Flag diabete" = 'Sim' OR "Flag hipertensão" = 'Sim'  OR "Flag doenças cardiovasculares" THEN 'Com Comorbidades'
            ELSE 'Sem Comorbidades'
        END AS tipo_comorbidade,  -- Classifica se o morador tem ou não comorbidades
        SUM(CASE WHEN "Flag febre" = 'Sim' THEN 1 ELSE 0 END) AS total_febre,  -- Total de febre
        SUM(CASE WHEN "Flag tosse" = 'Sim' THEN 1 ELSE 0 END) AS total_tosse,  -- Total de tosse
        SUM(CASE WHEN "Flag perda de sentidos" = 'Sim' THEN 1 ELSE 0 END) AS perda_de_sentidos,  -- Total de perda de sentidos
        COUNT(*) AS total_moradores  -- Total de moradores no grupo
    FROM
        base_covid
    WHERE
        "Flag diabete" IN ('Sim', 'Não') AND
        "Flag hipertensão" IN ('Sim', 'Não') AND -- Garante que as variáveis sejam válidas
        "Flag doenças cardiovasculares" IN ('Sim', 'Não')
    GROUP BY
        tipo_comorbidade  -- Agrupa por quem tem ou não comorbidades
)
SELECT
    tipo_comorbidade,
    total_febre,
    total_tosse,
    perda_de_sentidos,
    total_moradores
FROM
    comorbidades_sintomas
ORDER BY
    tipo_comorbidade DESC;

"""
result = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result)

tipo_comorbidade  total_febre  total_tosse  perda_de_sentidos  \
0  Sem Comorbidades         4773        15425               6417   
1  Com Comorbidades          994         2721                930   

   total_moradores  
0           890110  
1            90297

Apesar dos números absolutos serem muito maiores no grupo sem comorbidades, isso ocorre porque a base de moradores sem comorbidades é muito maior (mais de 10 vezes a quantidade de moradores com comorbidades). Assim, uma **comparação proporcional é mais adequada.**

In [ ]:
# comparando proporcionanete
query = """
WITH comorbidades_sintomas AS (
    SELECT
        CASE
            WHEN "Flag diabete" = 'Sim' OR "Flag hipertensão" = 'Sim' THEN 'Com Comorbidades'
            ELSE 'Sem Comorbidades'
        END AS tipo_comorbidade,  -- Classifica se o morador tem ou não comorbidades
        SUM(CASE WHEN "Flag febre" = 'Sim' THEN 1 ELSE 0 END) AS febre,  -- Total de febre
        SUM(CASE WHEN "Flag tosse" = 'Sim' THEN 1 ELSE 0 END) AS tosse,  -- Total de tosse
        SUM(CASE WHEN "Flag perda de sentidos" = 'Sim' THEN 1 ELSE 0 END) AS perda_de_sentidos,  -- Total de perda de sentidos
        COUNT(*) AS total_moradores  -- Total de moradores no grupo
    FROM
        base_covid
    WHERE
        "Flag diabete" IN ('Sim', 'Não') AND
        "Flag hipertensão" IN ('Sim', 'Não')  -- Garante que as variáveis sejam válidas
    GROUP BY
        tipo_comorbidade  -- Agrupa por quem tem ou não comorbidades
)
SELECT
    tipo_comorbidade,
    febre,
    ROUND(febre * 100.0 / total_moradores, 2) AS febre_percent,  -- Percentual de febre no grupo
    tosse,
    ROUND(tosse * 100.0 / total_moradores, 2) AS tosse_percent,  -- Percentual de tosse no grupo
    perda_de_sentidos,
    ROUND(perda_de_sentidos * 100.0 / total_moradores, 2) AS perda_de_sentidos_percent,  -- Percentual de perda de sentidos no grupo
    total_moradores
FROM
    comorbidades_sintomas
ORDER BY
    tipo_comorbidade DESC;


"""
result = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result)

tipo_comorbidade  febre  febre_percent  tosse  tosse_percent  \
0  Sem Comorbidades   9685           0.55  33353           1.89   
1  Com Comorbidades   2305           1.53   6178           4.11   

   perda_de_sentidos  perda_de_sentidos_percent  total_moradores  
0              17487                       0.99          1760711  
1               2781                       1.85           150479

Pessoas com comorbidades (ex.: diabetes, hipertensão) apresentam sintomas de COVID-19 **proporcionalmente mais frequentes** do que aquelas sem comorbidades:



*   Febre: 1,53% (com) vs. 0,55% (sem).
*   Tosse: 4,11% (com) vs. 1,89% (sem).
*   Perda de Sentidos: 1,85% (com) vs. 0,99% (sem).






Essas diferenças ocorrem devido ao sistema imunológico mais fragilizado e maior atenção aos sintomas no grupo com comorbidades.

In [67]:
#K-Quais estados têm maior frequência de sintomas em pessoas com comorbidades?
# comparando já proporcionanete
query = """
WITH moradores_comorbidades AS (
    SELECT
        UF,  -- Estado
        SUM(CASE WHEN "Flag febre" = 'Sim' THEN 1 ELSE 0 END) AS febre,  -- Total de casos com febre
        SUM(CASE WHEN "Flag tosse" = 'Sim' THEN 1 ELSE 0 END) AS tosse,  -- Total de casos com tosse
        SUM(CASE WHEN "Flag perda de sentidos" = 'Sim' THEN 1 ELSE 0 END) AS perda_de_sentidos,  -- Total de casos com perda de sentidos
        COUNT(*) AS total_comorbidades -- Total de moradores com comorbidades no estado
    FROM
        base_covid
    WHERE
        "Flag diabete" = 'Sim' OR
        "Flag hipertensão" = 'Sim' OR
        "Flag doenças respiratórias" = 'Sim' OR
        "Flag doenças cardiovasculares" = 'Sim'
    GROUP BY
        UF
),
sintomas_por_estado AS (
    SELECT
        UF,
        febre,
        tosse,
        perda_de_sentidos,
        total_comorbidades,
        (febre * 100.0 / total_comorbidades) AS febre_percent,  -- Percentual de casos com febre
        (tosse * 100.0 / total_comorbidades) AS tosse_percent,  -- Percentual de casos com tosse
        (perda_de_sentidos * 100.0 / total_comorbidades) AS perda_de_sentidos_percent -- Percentual de casos com perda de sentidos
    FROM
        moradores_comorbidades
)
SELECT
    UF,
    febre,
    febre_percent,
    tosse,
    tosse_percent,
    perda_de_sentidos,
    perda_de_sentidos_percent,
    total_comorbidades
FROM
    sintomas_por_estado
ORDER BY
    total_comorbidades DESC; -- Ordena pelos estados com mais moradores com comorbidades


"""
result10 = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result10)


UF  febre  febre_percent  tosse  tosse_percent  \
0          Minas Gerais    307       1.240404    889       3.591919   
1             São Paulo    337       1.541417    730       3.338975   
2     Rio Grande do Sul    286       1.576974    873       4.813630   
3        Rio de Janeiro    134       0.811285    346       2.094811   
4        Santa Catarina    172       1.199191    468       3.262916   
5                Paraná    148       1.114710    470       3.539956   
6              Maranhão     95       0.946027    315       3.136825   
7        Espírito Santo    125       1.397273    348       3.890007   
8                 Ceará     99       1.115744    291       3.279612   
9                 Goiás    150       1.718213    383       4.387171   
10           Pernambuco    102       1.213130    259       3.080400   
11                Bahia     94       1.137464    312       3.775411   
12                 Pará     96       1.327434    199       2.751659   
13              Paraíba     58       1.000000    283       4.879310   
14              Alagoas     75       1.323919    177       3.124448   
15          Mato Grosso     61       1.091820    180       3.221765   
16   Mato Grosso do Sul     63       1.282312    171       3.480562   
17  Rio Grande do Norte     52       1.062526    151       3.085411   
18              Sergipe     52       1.211274    209       4.868390   
19                Piauí     40       0.982318    103       2.529470   
20     Distrito Federal     82       2.035244    187       4.641350   
21             Amazonas     50       1.296344    114       2.955665   
22            Tocantins     40       1.536688    101       3.880138   
23             Rondônia     46       1.834131    100       3.987241   
24                 Acre     46       1.973402     92       3.946804   
25              Roraima     35       2.040816     62       3.615160   
26                Amapá     20       1.646091     41       3.374486   

    perda_de_sentidos  perda_de_sentidos_percent  total_comorbidades  
0                 386                   1.559596               24750  
1                 340                   1.555139               21863  
2                 375                   2.067711               18136  
3                 137                   0.829448               16517  
4                 214                   1.492017               14343  
5                 228                   1.717255               13277  
6                 126                   1.254730               10042  
7                 135                   1.509054                8946  
8                 124                   1.397498                8873  
9                 170                   1.947308                8730  
10                126                   1.498573                8408  
11                155                   1.875605                8264  
12                 84                   1.161504                7232  
13                 98                   1.689655                5800  
14                 86                   1.518094                5665  
15                 83                   1.485592                5587  
16                 68                   1.384083                4913  
17                 69                   1.409890                4894  
18                 65                   1.514093                4293  
19                 50                   1.227898                4072  
20                 85                   2.109705                4029  
21                 41                   1.063002                3857  
22                 47                   1.805609                2603  
23                 51                   2.033493                2508  
24                 42                   1.801802                2331  
25                 39                   2.274052                1715  
26                 19                   1.563786                1215

**Análises e hipóteses:**

População absoluta influencia os números totais: Estados com maior população de pessoas com comorbidades, como São Paulo e Minas Gerais, tendem a relatar mais casos absolutos de sintomas.

Percentuais elevados podem refletir maior vulnerabilidade: Estados como Distrito Federal, Roraima e Rondônia têm percentuais mais altos de sintomas, sugerindo uma maior vulnerabilidade dessa população ou possíveis diferenças no acesso a cuidados preventivos.

Tosse como o sintoma mais comum: Em praticamente todos os estados, a tosse é o sintoma mais frequentemente relatado, seguido por febre e perda de sentidos.

In [ ]:
#L- Há uma diferença no tipo de serviço de saúde procurado (público ou privado) por pessoas com comorbidades e sintomas?
query = """
WITH pessoas_comorbidades_sintomas AS (
    SELECT
        UF,
        CASE
            WHEN "Flag diabetes" = 'Sim' OR
                 "Flag hipertensão" = 'Sim' OR
                 "Flag doenças respiratórias" = 'Sim' OR
                 "Flag doenças cardiovasculares" = 'Sim' OR
                 "Flag doenças cancerigenas" = 'Sim'
            THEN 'Com Comorbidades'
            ELSE 'Sem Comorbidades'
        END AS tipo_comorbidade,
        CASE
            WHEN "Flag febre" = 'Sim' OR
                 "Flag tosse" = 'Sim' OR
                 "Flag perda de sentidos" = 'Sim'
            THEN 'Com Sintomas'
            ELSE 'Sem Sintomas'
        END AS tipo_sintomas,
        SUM(CASE WHEN "Local que buscou atendimento foi posto/UBS" = 'Sim' THEN 1 ELSE 0 END) AS atendimento_posto_ubs,
        SUM(CASE WHEN "Local que buscou atendimento foi pronto socorro do SUS/UPA" = 'Sim' THEN 1 ELSE 0 END) AS atendimento_pronto_socorro_sus,
        SUM(CASE WHEN "Local que buscou atendimento foi hospital do SUS" = 'Sim' THEN 1 ELSE 0 END) AS atendimento_hospital_sus,
        SUM(CASE WHEN "Local que buscou atendimento foi ambulatório ou consultório privado " = 'Sim' THEN 1 ELSE 0 END) AS atendimento_ambulatorio_privado,
        SUM(CASE WHEN "Local que buscou atendimento foi pronto socorro privado" = 'Sim' THEN 1 ELSE 0 END) AS atendimento_pronto_socorro_privado,
        SUM(CASE WHEN "Local que buscou atendimento foi hospital privado" = 'Sim' THEN 1 ELSE 0 END) AS atendimento_hospital_privado,
        COUNT(*) AS total_pessoas
    FROM
        base_covid
    WHERE
        ("Flag diabetes" = 'Sim' OR
         "Flag hipertensão" = 'Sim' OR
         "Flag doenças respiratórias" = 'Sim' OR
         "Flag doenças cardiovasculares" = 'Sim' OR
         "Flag doenças cancerigenas" = 'Sim')  -- Comorbidades
        AND
        ("Flag febre" = 'Sim' OR
         "Flag tosse" = 'Sim' OR
         "Flag perda de sentidos" = 'Sim')  -- Sintomas
    GROUP BY
        UF, tipo_comorbidade, tipo_sintomas
),
resumo_servico_saude AS (
    SELECT
        UF,
        tipo_comorbidade,
        tipo_sintomas,
        atendimento_posto_ubs,
        atendimento_pronto_socorro_sus,
        atendimento_hospital_sus,
        atendimento_ambulatorio_privado,
        atendimento_pronto_socorro_privado,
        atendimento_hospital_privado,
        total_pessoas,
        ROUND((atendimento_posto_ubs * 100.0 / total_pessoas), 2) AS percentual_posto_ubs,
        ROUND((atendimento_pronto_socorro_sus * 100.0 / total_pessoas), 2) AS percentual_pronto_socorro_sus,
        ROUND((atendimento_hospital_sus * 100.0 / total_pessoas), 2) AS percentual_hospital_sus,
        ROUND((atendimento_ambulatorio_privado * 100.0 / total_pessoas), 2) AS percentual_ambulatorio_privado,
        ROUND((atendimento_pronto_socorro_privado * 100.0 / total_pessoas), 2) AS percentual_pronto_socorro_privado,
        ROUND((atendimento_hospital_privado * 100.0 / total_pessoas), 2) AS percentual_hospital_privado
    FROM
        pessoas_comorbidades_sintomas
)
SELECT
    UF,
    tipo_comorbidade,
    tipo_sintomas,
    atendimento_posto_ubs,
    atendimento_pronto_socorro_sus,
    atendimento_hospital_sus,
    atendimento_ambulatorio_privado,
    atendimento_pronto_socorro_privado,
    atendimento_hospital_privado,
    percentual_posto_ubs,
    percentual_pronto_socorro_sus,
    percentual_hospital_sus,
    percentual_ambulatorio_privado,
    percentual_pronto_socorro_privado,
    percentual_hospital_privado,
    total_pessoas
FROM
    resumo_servico_saude
ORDER BY
    total_pessoas DESC;

"""
result = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result)


UF  tipo_comorbidade tipo_sintomas  \
0          Minas Gerais  Com Comorbidades  Com Sintomas   
1     Rio Grande do Sul  Com Comorbidades  Com Sintomas   
2             São Paulo  Com Comorbidades  Com Sintomas   
3                Paraná  Com Comorbidades  Com Sintomas   
4        Santa Catarina  Com Comorbidades  Com Sintomas   
5                 Goiás  Com Comorbidades  Com Sintomas   
6                 Bahia  Com Comorbidades  Com Sintomas   
7        Rio de Janeiro  Com Comorbidades  Com Sintomas   
8              Maranhão  Com Comorbidades  Com Sintomas   
9        Espírito Santo  Com Comorbidades  Com Sintomas   
10                Ceará  Com Comorbidades  Com Sintomas   
11           Pernambuco  Com Comorbidades  Com Sintomas   
12                 Pará  Com Comorbidades  Com Sintomas   
13              Paraíba  Com Comorbidades  Com Sintomas   
14          Mato Grosso  Com Comorbidades  Com Sintomas   
15     Distrito Federal  Com Comorbidades  Com Sintomas   
16              Sergipe  Com Comorbidades  Com Sintomas   
17              Alagoas  Com Comorbidades  Com Sintomas   
18   Mato Grosso do Sul  Com Comorbidades  Com Sintomas   
19  Rio Grande do Norte  Com Comorbidades  Com Sintomas   
20             Amazonas  Com Comorbidades  Com Sintomas   
21            Tocantins  Com Comorbidades  Com Sintomas   
22                Piauí  Com Comorbidades  Com Sintomas   
23             Rondônia  Com Comorbidades  Com Sintomas   
24                 Acre  Com Comorbidades  Com Sintomas   
25              Roraima  Com Comorbidades  Com Sintomas   
26                Amapá  Com Comorbidades  Com Sintomas   

    atendimento_posto_ubs  atendimento_pronto_socorro_sus  \
0                      83                              37   
1                     110                              28   
2                      63                              54   
3                      45                              29   
4                      69                              22   
5                      26                              22   
6                      28                               5   
7                      40                              36   
8                      14                               7   
9                      30                              32   
10                     16                               7   
11                     15                               5   
12                     26                              18   
13                     23                               1   
14                     22                              11   
15                     13                               7   
16                     14                               3   
17                     14                               4   
18                     15                               6   
19                     13                               3   
20                      6                               5   
21                     16                               3   
22                     13                               2   
23                     14                               9   
24                     11                               4   
25                     10                               5   
26                     11                               0   

    atendimento_hospital_sus  atendimento_ambulatorio_privado  \
0                         63                               44   
1                         55                               31   
2                         67                               31   
3                         31                               18   
4                         28                               13   
5                         68                               26   
6                         24                               15   
7                         30                               16   
8                         15                                8   
9        

**Análise dos resultados:**

**Maiores percentuais de atendimento em Postos/UBS:**

Amapá (13,1%): É o estado com maior percentual de pessoas com comorbidades e sintomas buscando atendimento em postos/UBS.
Santa Catarina (10,47%): Outro estado com alta proporção de atendimento nesse tipo de serviço.
Rio Grande do Sul (8,65%) e Tocantins (7,96%) também têm percentuais significativos.

**Estados com maior número absoluto de atendimentos em Postos/UBS:**

Minas Gerais (83 pessoas): Apresenta o maior número de pessoas buscando atendimento em postos/UBS.
Rio Grande do Sul (110 pessoas) e São Paulo (63 pessoas) seguem em volume absoluto, mas com percentuais mais baixos em relação ao total de atendimentos

**Atendimentos no setor privado:**

**Os estados com maior número de atendimentos em hospitais ou pronto-socorros privados são:**

São Paulo (396 pessoas).
Rio Grande do Sul (393 pessoas).
Minas Gerais (343 pessoas).


Isso indica que, em estados mais populosos, os serviços privados têm uma maior parcela dos atendimentos.
Estados com menor percentual de atendimento em Postos/UBS:

Maranhão (2,66%): É o estado com menor percentual de atendimento em postos/UBS para pessoas com comorbidades e sintomas.
Amazonas (2,62%) e Roraima (6,54%) também apresentam percentuais relativamente baixos, indicando uma menor dependência desse tipo de serviço ou menor cobertura.

**Observação de padrões:**


Estados menores ou menos populosos, como Amapá e Tocantins, apresentam maior dependência de postos/UBS para atendimento.
Estados mais populosos, como São Paulo, Minas Gerais e Rio Grande do Sul, têm maior número absoluto de atendimentos, mas seus percentuais em Postos/UBS são mais baixos, possivelmente devido à maior disponibilidade de serviços privados

In [ ]:
#M-Pessoas com comorbidades realizaram mais testes de COVID-19 em relação às que não possuem comorbidades?

query = """

WITH total_testes AS (
    SELECT
        CASE
            WHEN "Flag diabete" = 'Sim' OR
                 "Flag hipertensão" = 'Sim' OR
                 "Flag doenças respiratórias" = 'Sim' OR
                 "Flag doenças cardiovasculares" = 'Sim' OR
                 "Flag trastorno depressivo" = 'Sim' OR
                 "Flag doenças cancerigenas" = 'Sim'
            THEN 'Com Comorbidades'
            ELSE 'Sem Comorbidades'
        END AS tipo_comorbidade,
        COUNT(*) AS total_moradores,
        SUM(CASE WHEN "Tipo do teste (cotonete)" = 'Sim' THEN 1 ELSE 0 END) AS total_teste_cotonete,
        SUM(CASE WHEN "Tipo do teste (sanguineo)" = 'Sim' THEN 1 ELSE 0 END) AS total_teste_sanguineo
    FROM
        base_covid
    GROUP BY
        tipo_comorbidade
)
SELECT
    tipo_comorbidade,
    total_moradores,
    total_teste_cotonete,
    total_teste_sanguineo,
    (total_teste_cotonete * 100.0 / total_moradores) AS percentual_teste_cotonete,
    (total_teste_sanguineo * 100.0 / total_moradores) AS percentual_teste_sanguineo
FROM
    total_testes;

"""
result = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result)


tipo_comorbidade  total_moradores  total_teste_cotonete  \
0  Com Comorbidades           797170                 14310   
1  Sem Comorbidades          1122713                 18856   

   total_teste_sanguineo  percentual_teste_cotonete  \
0                 118948                   1.795100   
1                 122546                   1.679503   

   percentual_teste_sanguineo  
0                   14.921284  
1                   10.915167

Pessoas com comorbidades realizaram mais testes sanguíneos (14,92%) em comparação às sem comorbidades (10,92%), enquanto a diferença para o teste de cotonete foi mínima (1,80% vs. 1,68%). Isso indica que pessoas com comorbidades são mais propensas a buscar monitoramento médico, possivelmente devido à maior preocupação ou orientação médica.

In [ ]:
#N- Entre aqueles que testaram positivo para COVID-19, qual é a frequência de comorbidades e sintomas?
query = """
-- CTE para filtrar os moradores que testaram positivo para COVID-19
WITH positivos AS (
    SELECT
        -- Resultado do teste
        "Flag resultado teste covid (cotonete)" AS resultado_teste_cotonete,
        "Flag resultado teste covid (sanguineo)" AS resultado_teste_sanguineo,

        -- Determina o status como 'Positivo' se qualquer um dos testes for positivo
        CASE
            WHEN "Flag resultado teste covid (cotonete)" = 'Positivo'
                 OR "Flag resultado teste covid (sanguineo)" = 'Positivo'
            THEN 'Positivo'
            ELSE 'Não Positivo'
        END AS status_teste,

        -- Flags de sintomas (febre, tosse, perda de sentidos)
        "Flag febre" AS febre,
        "Flag tosse" AS tosse,
        "Flag perda de sentidos" AS perda_de_sentidos,


        -- Identifica se o indivíduo possui comorbidades
        CASE
            WHEN "Flag diabete" = 'Sim' OR
                 "Flag hipertensão" = 'Sim' OR
                 "Flag doenças respiratórias" = 'Sim' OR
                 "Flag doenças cardiovasculares" = 'Sim'
            THEN 'Com Comorbidades'
            ELSE 'Sem Comorbidades'
        END AS tipo_comorbidade
    FROM
        base_covid


    -- Filtra somente os moradores que testaram positivo em algum dos testes
    WHERE
        "Flag resultado teste covid (cotonete)" = 'Positivo'
        OR "Flag resultado teste covid (sanguineo)" = 'Positivo'
),

-- CTE para calcular a frequência dos sintomas por tipo de comorbidade
frequencia AS (
    SELECT
        tipo_comorbidade,  -- Tipo de comorbidade (Com Comorbidades ou Sem Comorbidades)
        -- Soma o total de pessoas com febre
        SUM(CASE WHEN febre = 'Sim' THEN 1 ELSE 0 END) AS total_febre,
        -- Soma o total de pessoas com tosse
        SUM(CASE WHEN tosse = 'Sim' THEN 1 ELSE 0 END) AS total_tosse,
        -- Soma o total de pessoas com perda de sentidos
        SUM(CASE WHEN perda_de_sentidos = 'Sim' THEN 1 ELSE 0 END) AS total_perda_de_sentidos,
        -- Conta o total de moradores positivos por tipo de comorbidade
        COUNT(*) AS total_positivos
    FROM
        positivos
    GROUP BY
        tipo_comorbidade -- Agrupa os resultados por tipo de comorbidade
)

-- Seleciona e apresenta os resultados finais
SELECT
    tipo_comorbidade,
    total_febre,
    -- Calcula o percentual de pessoas com febre em relação ao total de positivos
    ROUND(total_febre * 100.0 / total_positivos, 2) AS febre_percent,
    total_tosse,  -- Total de pessoas com tosse
    -- Calcula o percentual de pessoas com tosse em relação ao total de positivos
    ROUND(total_tosse * 100.0 / total_positivos, 2) AS tosse_percent,
    total_perda_de_sentidos,  -- Total de pessoas com perda de sentidos
    -- Calcula o percentual de pessoas com perda de sentidos em relação ao total de positivos
    ROUND(total_perda_de_sentidos * 100.0 / total_positivos, 2) AS perda_de_sentidos_percent,
    total_positivos  -- Total de pessoas que testaram positivo
FROM
    frequencia;



"""
result = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result)


tipo_comorbidade  total_febre  febre_percent  total_tosse  tosse_percent  \
0  Com Comorbidades         1002           4.92         1612           7.92   
1  Sem Comorbidades         2680           2.58         5105           4.92   

   total_perda_de_sentidos  perda_de_sentidos_percent  total_positivos  
0                     1079                       5.30            20347  
1                     4249                       4.09           103831

**Conclusões:**

**Frequência Maior em Comorbidades:**

O grupo com comorbidades tem maior percentual de sintomas (febre, tosse e perda de sentidos) em relação ao total de positivos, quando comparado ao grupo sem comorbidades.
Por exemplo, 7.92% do grupo com comorbidades relatou tosse, enquanto apenas 4.92% do grupo sem comorbidades apresentou o mesmo sintoma.

**Frequência Absoluta Maior em Sem Comorbidades:**

Em termos absolutos, o grupo sem comorbidades possui um maior número de pessoas com sintomas, devido à quantidade significativamente maior de indivíduos nesse grupo (103.831 contra 20.347).

**Destaque:**

A diferença nos percentuais sugere que pessoas com comorbidades apresentam sintomas em proporções mais altas, o que pode indicar maior vulnerabilidade ou maior propensão a desenvolver sintomas graves ao contrair COVID-19.

In [ ]:
#O- Pessoas com comorbidades (ex.: diabetes, hipertensão) são mais propensas a buscar atendimento médico ao apresentar sintomas?


query = """
WITH moradores_atendimento AS (
    SELECT
        CASE
            WHEN "Ida ao serviço de saúde" = 'Sim' OR
                 "Optou por receber a visita de um profissional da saúde SUS" = 'Sim' OR
                 "Optou por receber a visita de um profissional da saúde PARTICULAR" = 'Sim'
            THEN 'Buscou Atendimento'
            WHEN "optou por ficar em casa" = 'Sim' THEN 'Ficou em Casa'
            WHEN "Optou pela auto medicação" = 'Sim' THEN 'Auto-medicação'
            ELSE 'Outra Providência'
        END AS tipo_providencia, -- Classificação da providência tomada
        CASE
            WHEN "Flag diabete" = 'Sim' OR
                 "Flag hipertensão" = 'Sim' OR
                 "Flag doenças respiratórias" = 'Sim' OR
                 "Flag doenças cardiovasculares" = 'Sim'
            THEN 'Com Comorbidades'
            ELSE 'Sem Comorbidades'
        END AS tipo_comorbidade, -- Classificação por comorbidades
        COUNT(*) AS total_pessoas, -- Total de pessoas no grupo
        SUM(CASE WHEN "Local que buscou atendimento foi posto/UBS" = 'Sim' THEN 1 ELSE 0 END) AS atendimento_posto_ubs,
        SUM(CASE WHEN "Local que buscou atendimento foi pronto socorro do SUS/UPA" = 'Sim' THEN 1 ELSE 0 END) AS atendimento_pronto_socorro_sus,
        SUM(CASE WHEN "Local que buscou atendimento foi hospital do SUS" = 'Sim' THEN 1 ELSE 0 END) AS atendimento_hospital_sus,
        SUM(CASE WHEN "Local que buscou atendimento foi ambulatório ou consultório privado " = 'Sim' THEN 1 ELSE 0 END) AS atendimento_ambulatorio_privado,
        SUM(CASE WHEN "Local que buscou atendimento foi pronto socorro privado" = 'Sim' THEN 1 ELSE 0 END) AS atendimento_pronto_socorro_privado,
        SUM(CASE WHEN "Local que buscou atendimento foi hospital privado" = 'Sim' THEN 1 ELSE 0 END) AS atendimento_hospital_privado,
        SUM(CASE WHEN "Flag internação" = 'Sim' THEN 1 ELSE 0 END) AS total_internacoes
    FROM
        base_covid
    WHERE
        "Flag febre" = 'Sim' OR
        "Flag tosse" = 'Sim' OR
        "Flag perda de sentidos" = 'Sim' -- Filtra apenas pessoas com sintomas
    GROUP BY
        tipo_providencia, tipo_comorbidade
)
SELECT
    tipo_comorbidade,
    tipo_providencia,
    total_pessoas,
    atendimento_posto_ubs,
    atendimento_pronto_socorro_sus,
    atendimento_hospital_sus,
    atendimento_ambulatorio_privado,
    atendimento_pronto_socorro_privado,
    atendimento_hospital_privado,
    total_internacoes,
    ROUND(total_pessoas * 100.0 / SUM(total_pessoas) OVER (PARTITION BY tipo_comorbidade), 2) AS percentual_providencia,
    ROUND(total_internacoes * 100.0 / total_pessoas, 2) AS percentual_internacoes -- Percentual de internações
FROM
    moradores_atendimento
ORDER BY
    tipo_comorbidade, tipo_providencia DESC;

"""
result = pd.read_sql_query(query, conn)

# Exibir o resultado
display(result)


tipo_comorbidade    tipo_providencia  total_pessoas  atendimento_posto_ubs  \
0  Com Comorbidades   Outra Providência           2263                    275   
1  Com Comorbidades       Ficou em Casa           1842                      0   
2  Com Comorbidades  Buscou Atendimento           6014                    427   
3  Com Comorbidades      Auto-medicação            186                      0   
4  Sem Comorbidades   Outra Providência           9814                   1183   
5  Sem Comorbidades       Ficou em Casa           4439                      0   
6  Sem Comorbidades  Buscou Atendimento          27695                   1002   
7  Sem Comorbidades      Auto-medicação            401                      0   

   atendimento_pronto_socorro_sus  atendimento_hospital_sus  \
0                             111                       275   
1                               0                         0   
2                             206                       194   
3                               0                         0   
4                             477                      1327   
5                               0                         0   
6                             496                       428   
7                               0                         0   

   atendimento_ambulatorio_privado  atendimento_pronto_socorro_privado  \
0                              145                                  41   
1                                0                                   0   
2                              171                                  66   
3                                0                                   0   
4                              405                                 101   
5                                0                                   0   
6                              437                                 170   
7                                0                                   0   

   atendimento_hospital_privado  total_internacoes  percentual_providencia  \
0                           853                688                   21.96   
1                           230                142                   17.87   
2                          1163               1269                   58.36   
3                             2                  3                    1.80   
4                          3786               3553                   23.17   
5                           647                562                   10.48   
6                          4592               6927                   65.40   
7                             5                  7                    0.95   

   percentual_internacoes  
0                   30.40  
1                    7.71  
2                   21.10  
3                    1.61  
4                   36.20  
5                   12.66  
6                   25.01  
7                    1.75

**Conclusões**

Busca por atendimento: É mais comum para pessoas sem comorbidades, mas a diferença não é tão acentuada.

Taxa de internações: Pessoas com comorbidades que optaram por "Outra Providência" ou "Ficou em Casa" têm uma menor taxa de internações do que aquelas sem comorbidades.

Relação com comorbidades: A presença de comorbidades não necessariamente implica uma maior taxa de internação, mas pode influenciar o tipo de providência tomada.